/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  DeliveryCompliance as PrismaDeliveryCompliance,
  DeliveryRequest as PrismaDeliveryRequest,
  User as PrismaUser,
} from "@prisma/client";

export class DeliveryComplianceServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.DeliveryComplianceCountArgs, "select">
  ): Promise<number> {
    return this.prisma.deliveryCompliance.count(args);
  }

  async deliveryCompliances(
    args: Prisma.DeliveryComplianceFindManyArgs
  ): Promise<PrismaDeliveryCompliance[]> {
    return this.prisma.deliveryCompliance.findMany(args);
  }
  async deliveryCompliance(
    args: Prisma.DeliveryComplianceFindUniqueArgs
  ): Promise<PrismaDeliveryCompliance | null> {
    return this.prisma.deliveryCompliance.findUnique(args);
  }
  async createDeliveryCompliance(
    args: Prisma.DeliveryComplianceCreateArgs
  ): Promise<PrismaDeliveryCompliance> {
    return this.prisma.deliveryCompliance.create(args);
  }
  async updateDeliveryCompliance(
    args: Prisma.DeliveryComplianceUpdateArgs
  ): Promise<PrismaDeliveryCompliance> {
    return this.prisma.deliveryCompliance.update(args);
  }
  async deleteDeliveryCompliance(
    args: Prisma.DeliveryComplianceDeleteArgs
  ): Promise<PrismaDeliveryCompliance> {
    return this.prisma.deliveryCompliance.delete(args);
  }

  async getDelivery(parentId: string): Promise<PrismaDeliveryRequest | null> {
    return this.prisma.deliveryCompliance
      .findUnique({
        where: { id: parentId },
      })
      .delivery();
  }

  async getVerifiedBy(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.deliveryCompliance
      .findUnique({
        where: { id: parentId },
      })
      .verifiedBy();
  }
}
