/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  EvidenceExport as PrismaEvidenceExport,
  User as PrismaUser,
  DeliveryRequest as PrismaDeliveryRequest,
} from "@prisma/client";

export class EvidenceExportServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.EvidenceExportCountArgs, "select">
  ): Promise<number> {
    return this.prisma.evidenceExport.count(args);
  }

  async evidenceExports(
    args: Prisma.EvidenceExportFindManyArgs
  ): Promise<PrismaEvidenceExport[]> {
    return this.prisma.evidenceExport.findMany(args);
  }
  async evidenceExport(
    args: Prisma.EvidenceExportFindUniqueArgs
  ): Promise<PrismaEvidenceExport | null> {
    return this.prisma.evidenceExport.findUnique(args);
  }
  async createEvidenceExport(
    args: Prisma.EvidenceExportCreateArgs
  ): Promise<PrismaEvidenceExport> {
    return this.prisma.evidenceExport.create(args);
  }
  async updateEvidenceExport(
    args: Prisma.EvidenceExportUpdateArgs
  ): Promise<PrismaEvidenceExport> {
    return this.prisma.evidenceExport.update(args);
  }
  async deleteEvidenceExport(
    args: Prisma.EvidenceExportDeleteArgs
  ): Promise<PrismaEvidenceExport> {
    return this.prisma.evidenceExport.delete(args);
  }

  async getCreatedBy(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.evidenceExport
      .findUnique({
        where: { id: parentId },
      })
      .createdBy();
  }

  async getDelivery(parentId: string): Promise<PrismaDeliveryRequest | null> {
    return this.prisma.evidenceExport
      .findUnique({
        where: { id: parentId },
      })
      .delivery();
  }
}
