/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, DealerLead as PrismaDealerLead } from "@prisma/client";

export class DealerLeadServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.DealerLeadCountArgs, "select">
  ): Promise<number> {
    return this.prisma.dealerLead.count(args);
  }

  async dealerLeads(
    args: Prisma.DealerLeadFindManyArgs
  ): Promise<PrismaDealerLead[]> {
    return this.prisma.dealerLead.findMany(args);
  }
  async dealerLead(
    args: Prisma.DealerLeadFindUniqueArgs
  ): Promise<PrismaDealerLead | null> {
    return this.prisma.dealerLead.findUnique(args);
  }
  async createDealerLead(
    args: Prisma.DealerLeadCreateArgs
  ): Promise<PrismaDealerLead> {
    return this.prisma.dealerLead.create(args);
  }
  async updateDealerLead(
    args: Prisma.DealerLeadUpdateArgs
  ): Promise<PrismaDealerLead> {
    return this.prisma.dealerLead.update(args);
  }
  async deleteDealerLead(
    args: Prisma.DealerLeadDeleteArgs
  ): Promise<PrismaDealerLead> {
    return this.prisma.dealerLead.delete(args);
  }
}
