/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { NotificationEvent } from "./NotificationEvent";
import { NotificationEventCountArgs } from "./NotificationEventCountArgs";
import { NotificationEventFindManyArgs } from "./NotificationEventFindManyArgs";
import { NotificationEventFindUniqueArgs } from "./NotificationEventFindUniqueArgs";
import { CreateNotificationEventArgs } from "./CreateNotificationEventArgs";
import { UpdateNotificationEventArgs } from "./UpdateNotificationEventArgs";
import { DeleteNotificationEventArgs } from "./DeleteNotificationEventArgs";
import { User } from "../../user/base/User";
import { Customer } from "../../customer/base/Customer";
import { DeliveryRequest } from "../../deliveryRequest/base/DeliveryRequest";
import { Driver } from "../../driver/base/Driver";
import { NotificationEventService } from "../notificationEvent.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => NotificationEvent)
export class NotificationEventResolverBase {
  constructor(
    protected readonly service: NotificationEventService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "NotificationEvent",
    action: "read",
    possession: "any",
  })
  async _notificationEventsMeta(
    @graphql.Args() args: NotificationEventCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [NotificationEvent])
  @nestAccessControl.UseRoles({
    resource: "NotificationEvent",
    action: "read",
    possession: "any",
  })
  async notificationEvents(
    @graphql.Args() args: NotificationEventFindManyArgs
  ): Promise<NotificationEvent[]> {
    return this.service.notificationEvents(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => NotificationEvent, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "NotificationEvent",
    action: "read",
    possession: "own",
  })
  async notificationEvent(
    @graphql.Args() args: NotificationEventFindUniqueArgs
  ): Promise<NotificationEvent | null> {
    const result = await this.service.notificationEvent(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => NotificationEvent)
  @nestAccessControl.UseRoles({
    resource: "NotificationEvent",
    action: "create",
    possession: "any",
  })
  async createNotificationEvent(
    @graphql.Args() args: CreateNotificationEventArgs
  ): Promise<NotificationEvent> {
    return await this.service.createNotificationEvent({
      ...args,
      data: {
        ...args.data,

        actor: args.data.actor
          ? {
              connect: args.data.actor,
            }
          : undefined,

        customer: args.data.customer
          ? {
              connect: args.data.customer,
            }
          : undefined,

        delivery: args.data.delivery
          ? {
              connect: args.data.delivery,
            }
          : undefined,

        driver: args.data.driver
          ? {
              connect: args.data.driver,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => NotificationEvent)
  @nestAccessControl.UseRoles({
    resource: "NotificationEvent",
    action: "update",
    possession: "any",
  })
  async updateNotificationEvent(
    @graphql.Args() args: UpdateNotificationEventArgs
  ): Promise<NotificationEvent | null> {
    try {
      return await this.service.updateNotificationEvent({
        ...args,
        data: {
          ...args.data,

          actor: args.data.actor
            ? {
                connect: args.data.actor,
              }
            : undefined,

          customer: args.data.customer
            ? {
                connect: args.data.customer,
              }
            : undefined,

          delivery: args.data.delivery
            ? {
                connect: args.data.delivery,
              }
            : undefined,

          driver: args.data.driver
            ? {
                connect: args.data.driver,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => NotificationEvent)
  @nestAccessControl.UseRoles({
    resource: "NotificationEvent",
    action: "delete",
    possession: "any",
  })
  async deleteNotificationEvent(
    @graphql.Args() args: DeleteNotificationEventArgs
  ): Promise<NotificationEvent | null> {
    try {
      return await this.service.deleteNotificationEvent(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "actor",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getActor(
    @graphql.Parent() parent: NotificationEvent
  ): Promise<User | null> {
    const result = await this.service.getActor(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Customer, {
    nullable: true,
    name: "customer",
  })
  @nestAccessControl.UseRoles({
    resource: "Customer",
    action: "read",
    possession: "any",
  })
  async getCustomer(
    @graphql.Parent() parent: NotificationEvent
  ): Promise<Customer | null> {
    const result = await this.service.getCustomer(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => DeliveryRequest, {
    nullable: true,
    name: "delivery",
  })
  @nestAccessControl.UseRoles({
    resource: "DeliveryRequest",
    action: "read",
    possession: "any",
  })
  async getDelivery(
    @graphql.Parent() parent: NotificationEvent
  ): Promise<DeliveryRequest | null> {
    const result = await this.service.getDelivery(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Driver, {
    nullable: true,
    name: "driver",
  })
  @nestAccessControl.UseRoles({
    resource: "Driver",
    action: "read",
    possession: "any",
  })
  async getDriver(
    @graphql.Parent() parent: NotificationEvent
  ): Promise<Driver | null> {
    const result = await this.service.getDriver(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
