/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  NotificationEvent as PrismaNotificationEvent,
  User as PrismaUser,
  Customer as PrismaCustomer,
  DeliveryRequest as PrismaDeliveryRequest,
  Driver as PrismaDriver,
} from "@prisma/client";

export class NotificationEventServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.NotificationEventCountArgs, "select">
  ): Promise<number> {
    return this.prisma.notificationEvent.count(args);
  }

  async notificationEvents(
    args: Prisma.NotificationEventFindManyArgs
  ): Promise<PrismaNotificationEvent[]> {
    return this.prisma.notificationEvent.findMany(args);
  }
  async notificationEvent(
    args: Prisma.NotificationEventFindUniqueArgs
  ): Promise<PrismaNotificationEvent | null> {
    return this.prisma.notificationEvent.findUnique(args);
  }
  async createNotificationEvent(
    args: Prisma.NotificationEventCreateArgs
  ): Promise<PrismaNotificationEvent> {
    return this.prisma.notificationEvent.create(args);
  }
  async updateNotificationEvent(
    args: Prisma.NotificationEventUpdateArgs
  ): Promise<PrismaNotificationEvent> {
    return this.prisma.notificationEvent.update(args);
  }
  async deleteNotificationEvent(
    args: Prisma.NotificationEventDeleteArgs
  ): Promise<PrismaNotificationEvent> {
    return this.prisma.notificationEvent.delete(args);
  }

  async getActor(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.notificationEvent
      .findUnique({
        where: { id: parentId },
      })
      .actor();
  }

  async getCustomer(parentId: string): Promise<PrismaCustomer | null> {
    return this.prisma.notificationEvent
      .findUnique({
        where: { id: parentId },
      })
      .customer();
  }

  async getDelivery(parentId: string): Promise<PrismaDeliveryRequest | null> {
    return this.prisma.notificationEvent
      .findUnique({
        where: { id: parentId },
      })
      .delivery();
  }

  async getDriver(parentId: string): Promise<PrismaDriver | null> {
    return this.prisma.notificationEvent
      .findUnique({
        where: { id: parentId },
      })
      .driver();
  }
}
