/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsBoolean,
  ValidateNested,
  IsOptional,
  IsInt,
  Max,
  IsDate,
  IsEnum,
  IsString,
  MaxLength,
  IsNumber,
} from "class-validator";

import { DeliveryAssignment } from "../../deliveryAssignment/base/DeliveryAssignment";
import { Type } from "class-transformer";
import { AdminAuditLog } from "../../adminAuditLog/base/AdminAuditLog";
import { DeliveryCompliance } from "../../deliveryCompliance/base/DeliveryCompliance";
import { User } from "../../user/base/User";
import { EnumDeliveryRequestCreatedByRole } from "./EnumDeliveryRequestCreatedByRole";
import { Customer } from "../../customer/base/Customer";
import { EnumDeliveryRequestCustomerChose } from "./EnumDeliveryRequestCustomerChose";
import { DisputeCase } from "../../disputeCase/base/DisputeCase";
import { DeliveryEvidence } from "../../deliveryEvidence/base/DeliveryEvidence";
import { EvidenceExport } from "../../evidenceExport/base/EvidenceExport";
import { NotificationEvent } from "../../notificationEvent/base/NotificationEvent";
import { Payment } from "../../payment/base/Payment";
import { DriverPayout } from "../../driverPayout/base/DriverPayout";
import { Quote } from "../../quote/base/Quote";
import { DeliveryRating } from "../../deliveryRating/base/DeliveryRating";
import { ScheduleChangeRequest } from "../../scheduleChangeRequest/base/ScheduleChangeRequest";
import { EnumDeliveryRequestServiceType } from "./EnumDeliveryRequestServiceType";
import { EnumDeliveryRequestStatus } from "./EnumDeliveryRequestStatus";
import { DeliveryStatusHistory } from "../../deliveryStatusHistory/base/DeliveryStatusHistory";
import { SupportRequest } from "../../supportRequest/base/SupportRequest";
import { Tip } from "../../tip/base/Tip";
import { TrackingSession } from "../../trackingSession/base/TrackingSession";

@ObjectType()
class DeliveryRequest {
  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  afterHours!: boolean;

  @ApiProperty({
    required: false,
    type: () => [DeliveryAssignment],
  })
  @ValidateNested()
  @Type(() => DeliveryAssignment)
  @IsOptional()
  assignments?: Array<DeliveryAssignment>;

  @ApiProperty({
    required: false,
    type: () => [AdminAuditLog],
  })
  @ValidateNested()
  @Type(() => AdminAuditLog)
  @IsOptional()
  audits?: Array<AdminAuditLog>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  bufferMinutes!: number | null;

  @ApiProperty({
    required: false,
    type: () => DeliveryCompliance,
  })
  @ValidateNested()
  @Type(() => DeliveryCompliance)
  @IsOptional()
  compliance?: DeliveryCompliance | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: () => User,
  })
  @ValidateNested()
  @Type(() => User)
  @IsOptional()
  createdBy?: User | null;

  @ApiProperty({
    required: false,
    enum: EnumDeliveryRequestCreatedByRole,
  })
  @IsEnum(EnumDeliveryRequestCreatedByRole)
  @IsOptional()
  @Field(() => EnumDeliveryRequestCreatedByRole, {
    nullable: true,
  })
  createdByRole?:
    | "PRIVATE_CUSTOMER"
    | "BUSINESS_CUSTOMER"
    | "DRIVER"
    | "ADMIN"
    | null;

  @ApiProperty({
    required: true,
    type: () => Customer,
  })
  @ValidateNested()
  @Type(() => Customer)
  customer?: Customer;

  @ApiProperty({
    required: false,
    enum: EnumDeliveryRequestCustomerChose,
  })
  @IsEnum(EnumDeliveryRequestCustomerChose)
  @IsOptional()
  @Field(() => EnumDeliveryRequestCustomerChose, {
    nullable: true,
  })
  customerChose?: "PICKUP_WINDOW" | "DROPOFF_WINDOW" | null;

  @ApiProperty({
    required: false,
    type: () => DisputeCase,
  })
  @ValidateNested()
  @Type(() => DisputeCase)
  @IsOptional()
  dispute?: DisputeCase | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  dropoffAddress!: string;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  dropoffLat!: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  dropoffLng!: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  dropoffPlaceId!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  dropoffState!: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  dropoffWindowEnd!: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  dropoffWindowStart!: Date | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  etaMinutes!: number | null;

  @ApiProperty({
    required: false,
    type: () => [DeliveryEvidence],
  })
  @ValidateNested()
  @Type(() => DeliveryEvidence)
  @IsOptional()
  evidence?: Array<DeliveryEvidence>;

  @ApiProperty({
    required: false,
    type: () => [EvidenceExport],
  })
  @ValidateNested()
  @Type(() => EvidenceExport)
  @IsOptional()
  evidenceExports?: Array<EvidenceExport>;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  isUrgent!: boolean;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  licensePlate!: string | null;

  @ApiProperty({
    required: false,
    type: () => [NotificationEvent],
  })
  @ValidateNested()
  @Type(() => NotificationEvent)
  @IsOptional()
  notifications?: Array<NotificationEvent>;

  @ApiProperty({
    required: false,
    type: () => Payment,
  })
  @ValidateNested()
  @Type(() => Payment)
  @IsOptional()
  payment?: Payment | null;

  @ApiProperty({
    required: false,
    type: () => DriverPayout,
  })
  @ValidateNested()
  @Type(() => DriverPayout)
  @IsOptional()
  payout?: DriverPayout | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  pickupAddress!: string;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  pickupLat!: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  pickupLng!: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  pickupPlaceId!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  pickupState!: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  pickupWindowEnd!: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  pickupWindowStart!: Date | null;

  @ApiProperty({
    required: false,
    type: () => Quote,
  })
  @ValidateNested()
  @Type(() => Quote)
  @IsOptional()
  quote?: Quote | null;

  @ApiProperty({
    required: false,
    type: () => DeliveryRating,
  })
  @ValidateNested()
  @Type(() => DeliveryRating)
  @IsOptional()
  rating?: DeliveryRating | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  recipientEmail!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  recipientName!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  recipientPhone!: string | null;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  requiresOpsConfirmation!: boolean;

  @ApiProperty({
    required: false,
    type: () => [DeliveryRequest],
  })
  @ValidateNested()
  @Type(() => DeliveryRequest)
  @IsOptional()
  resubmissions?: Array<DeliveryRequest>;

  @ApiProperty({
    required: false,
    type: () => DeliveryRequest,
  })
  @ValidateNested()
  @Type(() => DeliveryRequest)
  @IsOptional()
  resubmittedFrom?: DeliveryRequest | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  sameDayEligible!: boolean | null;

  @ApiProperty({
    required: false,
    type: () => [ScheduleChangeRequest],
  })
  @ValidateNested()
  @Type(() => ScheduleChangeRequest)
  @IsOptional()
  scheduleChanges?: Array<ScheduleChangeRequest>;

  @ApiProperty({
    required: true,
    enum: EnumDeliveryRequestServiceType,
  })
  @IsEnum(EnumDeliveryRequestServiceType)
  @Field(() => EnumDeliveryRequestServiceType, {
    nullable: true,
  })
  serviceType?: "HOME_DELIVERY" | "BETWEEN_LOCATIONS" | "SERVICE_PICKUP_RETURN";

  @ApiProperty({
    required: true,
    enum: EnumDeliveryRequestStatus,
  })
  @IsEnum(EnumDeliveryRequestStatus)
  @Field(() => EnumDeliveryRequestStatus, {
    nullable: true,
  })
  status?:
    | "DRAFT"
    | "QUOTED"
    | "LISTED"
    | "BOOKED"
    | "ACTIVE"
    | "COMPLETED"
    | "CANCELLED"
    | "EXPIRED"
    | "DISPUTED";

  @ApiProperty({
    required: false,
    type: () => [DeliveryStatusHistory],
  })
  @ValidateNested()
  @Type(() => DeliveryStatusHistory)
  @IsOptional()
  statusHistory?: Array<DeliveryStatusHistory>;

  @ApiProperty({
    required: false,
    type: () => [SupportRequest],
  })
  @ValidateNested()
  @Type(() => SupportRequest)
  @IsOptional()
  supportRequests?: Array<SupportRequest>;

  @ApiProperty({
    required: false,
    type: () => Tip,
  })
  @ValidateNested()
  @Type(() => Tip)
  @IsOptional()
  tip?: Tip | null;

  @ApiProperty({
    required: false,
    type: () => TrackingSession,
  })
  @ValidateNested()
  @Type(() => TrackingSession)
  @IsOptional()
  trackingSession?: TrackingSession | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  trackingShareExpiresAt!: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  trackingShareToken!: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  urgentBonusAmount!: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  vehicleColor!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  vehicleMake!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  vehicleModel!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  vinVerificationCode!: string | null;
}

export { DeliveryRequest as DeliveryRequest };
