/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AdminAuditLogCreateNestedManyWithoutUsersInput } from "./AdminAuditLogCreateNestedManyWithoutUsersInput";
import {
  ValidateNested,
  IsOptional,
  IsDate,
  IsString,
  MaxLength,
  IsBoolean,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { DeliveryAssignmentCreateNestedManyWithoutUsersInput } from "./DeliveryAssignmentCreateNestedManyWithoutUsersInput";
import { DeliveryComplianceCreateNestedManyWithoutUsersInput } from "./DeliveryComplianceCreateNestedManyWithoutUsersInput";
import { CustomerWhereUniqueInput } from "../../customer/base/CustomerWhereUniqueInput";
import { CustomerCreateNestedManyWithoutUsersInput } from "./CustomerCreateNestedManyWithoutUsersInput";
import { DeliveryRequestCreateNestedManyWithoutUsersInput } from "./DeliveryRequestCreateNestedManyWithoutUsersInput";
import { DisputeNoteCreateNestedManyWithoutUsersInput } from "./DisputeNoteCreateNestedManyWithoutUsersInput";
import { DriverWhereUniqueInput } from "../../driver/base/DriverWhereUniqueInput";
import { DriverCreateNestedManyWithoutUsersInput } from "./DriverCreateNestedManyWithoutUsersInput";
import { EvidenceExportCreateNestedManyWithoutUsersInput } from "./EvidenceExportCreateNestedManyWithoutUsersInput";
import { NotificationEventCreateNestedManyWithoutUsersInput } from "./NotificationEventCreateNestedManyWithoutUsersInput";
import { EnumUserRoles } from "./EnumUserRoles";
import { ScheduleChangeRequestCreateNestedManyWithoutUsersInput } from "./ScheduleChangeRequestCreateNestedManyWithoutUsersInput";
import { DeliveryStatusHistoryCreateNestedManyWithoutUsersInput } from "./DeliveryStatusHistoryCreateNestedManyWithoutUsersInput";
import { SupportRequestNoteCreateNestedManyWithoutUsersInput } from "./SupportRequestNoteCreateNestedManyWithoutUsersInput";
import { SupportRequestCreateNestedManyWithoutUsersInput } from "./SupportRequestCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: () => AdminAuditLogCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => AdminAuditLogCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => AdminAuditLogCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  adminActions?: AdminAuditLogCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => DeliveryAssignmentCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => DeliveryAssignmentCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => DeliveryAssignmentCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  assignmentsMade?: DeliveryAssignmentCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => AdminAuditLogCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => AdminAuditLogCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => AdminAuditLogCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  auditTargets?: AdminAuditLogCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => DeliveryComplianceCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => DeliveryComplianceCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => DeliveryComplianceCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  compliancesVerified?: DeliveryComplianceCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => CustomerWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CustomerWhereUniqueInput)
  @IsOptional()
  @Field(() => CustomerWhereUniqueInput, {
    nullable: true,
  })
  customer?: CustomerWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => CustomerCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CustomerCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CustomerCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  customersApproved?: CustomerCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => DeliveryRequestCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => DeliveryRequestCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => DeliveryRequestCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  deliveriesCreated?: DeliveryRequestCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  disabledAt?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  disabledReason?: string | null;

  @ApiProperty({
    required: false,
    type: () => DisputeNoteCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => DisputeNoteCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => DisputeNoteCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  disputeNotesAuthored?: DisputeNoteCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => DriverWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DriverWhereUniqueInput)
  @IsOptional()
  @Field(() => DriverWhereUniqueInput, {
    nullable: true,
  })
  driver?: DriverWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => DriverCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => DriverCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => DriverCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  driversApproved?: DriverCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  email!: string;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  emailVerifiedAt?: Date | null;

  @ApiProperty({
    required: false,
    type: () => EvidenceExportCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => EvidenceExportCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => EvidenceExportCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  exportsCreated?: EvidenceExportCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fullName?: string | null;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  isActive!: boolean;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  lastLoginAt?: Date | null;

  @ApiProperty({
    required: false,
    type: () => NotificationEventCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => NotificationEventCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => NotificationEventCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  notifEvents?: NotificationEventCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  passwordHash?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone?: string | null;

  @ApiProperty({
    required: true,
    enum: EnumUserRoles,
  })
  @IsEnum(EnumUserRoles)
  @Field(() => EnumUserRoles)
  roles!: "PRIVATE_CUSTOMER" | "BUSINESS_CUSTOMER" | "DRIVER" | "ADMIN";

  @ApiProperty({
    required: false,
    type: () => ScheduleChangeRequestCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ScheduleChangeRequestCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ScheduleChangeRequestCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  scheduleChangesDecided?: ScheduleChangeRequestCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => ScheduleChangeRequestCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ScheduleChangeRequestCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ScheduleChangeRequestCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  scheduleChangesRequested?: ScheduleChangeRequestCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => DeliveryStatusHistoryCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => DeliveryStatusHistoryCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => DeliveryStatusHistoryCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  statusActions?: DeliveryStatusHistoryCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => SupportRequestNoteCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SupportRequestNoteCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SupportRequestNoteCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  supportRequestNotesAuthored?: SupportRequestNoteCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => SupportRequestCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SupportRequestCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SupportRequestCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  supportRequestsAssigned?: SupportRequestCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => SupportRequestCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SupportRequestCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SupportRequestCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  supportRequestsRaised?: SupportRequestCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  username!: string;
}

export { UserCreateInput as UserCreateInput };
