/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { User } from "./User";
import { UserCountArgs } from "./UserCountArgs";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserFindUniqueArgs } from "./UserFindUniqueArgs";
import { CreateUserArgs } from "./CreateUserArgs";
import { UpdateUserArgs } from "./UpdateUserArgs";
import { DeleteUserArgs } from "./DeleteUserArgs";
import { AdminAuditLogFindManyArgs } from "../../adminAuditLog/base/AdminAuditLogFindManyArgs";
import { AdminAuditLog } from "../../adminAuditLog/base/AdminAuditLog";
import { DeliveryAssignmentFindManyArgs } from "../../deliveryAssignment/base/DeliveryAssignmentFindManyArgs";
import { DeliveryAssignment } from "../../deliveryAssignment/base/DeliveryAssignment";
import { DeliveryComplianceFindManyArgs } from "../../deliveryCompliance/base/DeliveryComplianceFindManyArgs";
import { DeliveryCompliance } from "../../deliveryCompliance/base/DeliveryCompliance";
import { CustomerFindManyArgs } from "../../customer/base/CustomerFindManyArgs";
import { Customer } from "../../customer/base/Customer";
import { DeliveryRequestFindManyArgs } from "../../deliveryRequest/base/DeliveryRequestFindManyArgs";
import { DeliveryRequest } from "../../deliveryRequest/base/DeliveryRequest";
import { DisputeNoteFindManyArgs } from "../../disputeNote/base/DisputeNoteFindManyArgs";
import { DisputeNote } from "../../disputeNote/base/DisputeNote";
import { DriverFindManyArgs } from "../../driver/base/DriverFindManyArgs";
import { Driver } from "../../driver/base/Driver";
import { EvidenceExportFindManyArgs } from "../../evidenceExport/base/EvidenceExportFindManyArgs";
import { EvidenceExport } from "../../evidenceExport/base/EvidenceExport";
import { NotificationEventFindManyArgs } from "../../notificationEvent/base/NotificationEventFindManyArgs";
import { NotificationEvent } from "../../notificationEvent/base/NotificationEvent";
import { ScheduleChangeRequestFindManyArgs } from "../../scheduleChangeRequest/base/ScheduleChangeRequestFindManyArgs";
import { ScheduleChangeRequest } from "../../scheduleChangeRequest/base/ScheduleChangeRequest";
import { DeliveryStatusHistoryFindManyArgs } from "../../deliveryStatusHistory/base/DeliveryStatusHistoryFindManyArgs";
import { DeliveryStatusHistory } from "../../deliveryStatusHistory/base/DeliveryStatusHistory";
import { SupportRequestNoteFindManyArgs } from "../../supportRequestNote/base/SupportRequestNoteFindManyArgs";
import { SupportRequestNote } from "../../supportRequestNote/base/SupportRequestNote";
import { SupportRequestFindManyArgs } from "../../supportRequest/base/SupportRequestFindManyArgs";
import { SupportRequest } from "../../supportRequest/base/SupportRequest";
import { UserService } from "../user.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => User)
export class UserResolverBase {
  constructor(
    protected readonly service: UserService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async _usersMeta(
    @graphql.Args() args: UserCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [User])
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async users(@graphql.Args() args: UserFindManyArgs): Promise<User[]> {
    return this.service.users(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "own",
  })
  async user(@graphql.Args() args: UserFindUniqueArgs): Promise<User | null> {
    const result = await this.service.user(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => User)
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "create",
    possession: "any",
  })
  async createUser(@graphql.Args() args: CreateUserArgs): Promise<User> {
    return await this.service.createUser({
      ...args,
      data: {
        ...args.data,

        customer: args.data.customer
          ? {
              connect: args.data.customer,
            }
          : undefined,

        driver: args.data.driver
          ? {
              connect: args.data.driver,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => User)
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async updateUser(@graphql.Args() args: UpdateUserArgs): Promise<User | null> {
    try {
      return await this.service.updateUser({
        ...args,
        data: {
          ...args.data,

          customer: args.data.customer
            ? {
                connect: args.data.customer,
              }
            : undefined,

          driver: args.data.driver
            ? {
                connect: args.data.driver,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => User)
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "delete",
    possession: "any",
  })
  async deleteUser(@graphql.Args() args: DeleteUserArgs): Promise<User | null> {
    try {
      return await this.service.deleteUser(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [AdminAuditLog], { name: "adminActions" })
  @nestAccessControl.UseRoles({
    resource: "AdminAuditLog",
    action: "read",
    possession: "any",
  })
  async findAdminActions(
    @graphql.Parent() parent: User,
    @graphql.Args() args: AdminAuditLogFindManyArgs
  ): Promise<AdminAuditLog[]> {
    const results = await this.service.findAdminActions(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [DeliveryAssignment], { name: "assignmentsMade" })
  @nestAccessControl.UseRoles({
    resource: "DeliveryAssignment",
    action: "read",
    possession: "any",
  })
  async findAssignmentsMade(
    @graphql.Parent() parent: User,
    @graphql.Args() args: DeliveryAssignmentFindManyArgs
  ): Promise<DeliveryAssignment[]> {
    const results = await this.service.findAssignmentsMade(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [AdminAuditLog], { name: "auditTargets" })
  @nestAccessControl.UseRoles({
    resource: "AdminAuditLog",
    action: "read",
    possession: "any",
  })
  async findAuditTargets(
    @graphql.Parent() parent: User,
    @graphql.Args() args: AdminAuditLogFindManyArgs
  ): Promise<AdminAuditLog[]> {
    const results = await this.service.findAuditTargets(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [DeliveryCompliance], {
    name: "compliancesVerified",
  })
  @nestAccessControl.UseRoles({
    resource: "DeliveryCompliance",
    action: "read",
    possession: "any",
  })
  async findCompliancesVerified(
    @graphql.Parent() parent: User,
    @graphql.Args() args: DeliveryComplianceFindManyArgs
  ): Promise<DeliveryCompliance[]> {
    const results = await this.service.findCompliancesVerified(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Customer], { name: "customersApproved" })
  @nestAccessControl.UseRoles({
    resource: "Customer",
    action: "read",
    possession: "any",
  })
  async findCustomersApproved(
    @graphql.Parent() parent: User,
    @graphql.Args() args: CustomerFindManyArgs
  ): Promise<Customer[]> {
    const results = await this.service.findCustomersApproved(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [DeliveryRequest], { name: "deliveriesCreated" })
  @nestAccessControl.UseRoles({
    resource: "DeliveryRequest",
    action: "read",
    possession: "any",
  })
  async findDeliveriesCreated(
    @graphql.Parent() parent: User,
    @graphql.Args() args: DeliveryRequestFindManyArgs
  ): Promise<DeliveryRequest[]> {
    const results = await this.service.findDeliveriesCreated(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [DisputeNote], { name: "disputeNotesAuthored" })
  @nestAccessControl.UseRoles({
    resource: "DisputeNote",
    action: "read",
    possession: "any",
  })
  async findDisputeNotesAuthored(
    @graphql.Parent() parent: User,
    @graphql.Args() args: DisputeNoteFindManyArgs
  ): Promise<DisputeNote[]> {
    const results = await this.service.findDisputeNotesAuthored(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Driver], { name: "driversApproved" })
  @nestAccessControl.UseRoles({
    resource: "Driver",
    action: "read",
    possession: "any",
  })
  async findDriversApproved(
    @graphql.Parent() parent: User,
    @graphql.Args() args: DriverFindManyArgs
  ): Promise<Driver[]> {
    const results = await this.service.findDriversApproved(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [EvidenceExport], { name: "exportsCreated" })
  @nestAccessControl.UseRoles({
    resource: "EvidenceExport",
    action: "read",
    possession: "any",
  })
  async findExportsCreated(
    @graphql.Parent() parent: User,
    @graphql.Args() args: EvidenceExportFindManyArgs
  ): Promise<EvidenceExport[]> {
    const results = await this.service.findExportsCreated(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [NotificationEvent], { name: "notifEvents" })
  @nestAccessControl.UseRoles({
    resource: "NotificationEvent",
    action: "read",
    possession: "any",
  })
  async findNotifEvents(
    @graphql.Parent() parent: User,
    @graphql.Args() args: NotificationEventFindManyArgs
  ): Promise<NotificationEvent[]> {
    const results = await this.service.findNotifEvents(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [ScheduleChangeRequest], {
    name: "scheduleChangesDecided",
  })
  @nestAccessControl.UseRoles({
    resource: "ScheduleChangeRequest",
    action: "read",
    possession: "any",
  })
  async findScheduleChangesDecided(
    @graphql.Parent() parent: User,
    @graphql.Args() args: ScheduleChangeRequestFindManyArgs
  ): Promise<ScheduleChangeRequest[]> {
    const results = await this.service.findScheduleChangesDecided(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [ScheduleChangeRequest], {
    name: "scheduleChangesRequested",
  })
  @nestAccessControl.UseRoles({
    resource: "ScheduleChangeRequest",
    action: "read",
    possession: "any",
  })
  async findScheduleChangesRequested(
    @graphql.Parent() parent: User,
    @graphql.Args() args: ScheduleChangeRequestFindManyArgs
  ): Promise<ScheduleChangeRequest[]> {
    const results = await this.service.findScheduleChangesRequested(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [DeliveryStatusHistory], {
    name: "statusActions",
  })
  @nestAccessControl.UseRoles({
    resource: "DeliveryStatusHistory",
    action: "read",
    possession: "any",
  })
  async findStatusActions(
    @graphql.Parent() parent: User,
    @graphql.Args() args: DeliveryStatusHistoryFindManyArgs
  ): Promise<DeliveryStatusHistory[]> {
    const results = await this.service.findStatusActions(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [SupportRequestNote], {
    name: "supportRequestNotesAuthored",
  })
  @nestAccessControl.UseRoles({
    resource: "SupportRequestNote",
    action: "read",
    possession: "any",
  })
  async findSupportRequestNotesAuthored(
    @graphql.Parent() parent: User,
    @graphql.Args() args: SupportRequestNoteFindManyArgs
  ): Promise<SupportRequestNote[]> {
    const results = await this.service.findSupportRequestNotesAuthored(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [SupportRequest], {
    name: "supportRequestsAssigned",
  })
  @nestAccessControl.UseRoles({
    resource: "SupportRequest",
    action: "read",
    possession: "any",
  })
  async findSupportRequestsAssigned(
    @graphql.Parent() parent: User,
    @graphql.Args() args: SupportRequestFindManyArgs
  ): Promise<SupportRequest[]> {
    const results = await this.service.findSupportRequestsAssigned(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [SupportRequest], {
    name: "supportRequestsRaised",
  })
  @nestAccessControl.UseRoles({
    resource: "SupportRequest",
    action: "read",
    possession: "any",
  })
  async findSupportRequestsRaised(
    @graphql.Parent() parent: User,
    @graphql.Args() args: SupportRequestFindManyArgs
  ): Promise<SupportRequest[]> {
    const results = await this.service.findSupportRequestsRaised(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Customer, {
    nullable: true,
    name: "customer",
  })
  @nestAccessControl.UseRoles({
    resource: "Customer",
    action: "read",
    possession: "any",
  })
  async getCustomer(@graphql.Parent() parent: User): Promise<Customer | null> {
    const result = await this.service.getCustomer(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Driver, {
    nullable: true,
    name: "driver",
  })
  @nestAccessControl.UseRoles({
    resource: "Driver",
    action: "read",
    possession: "any",
  })
  async getDriver(@graphql.Parent() parent: User): Promise<Driver | null> {
    const result = await this.service.getDriver(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
