/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AdminAuditLogListRelationFilter } from "../../adminAuditLog/base/AdminAuditLogListRelationFilter";
import { ValidateNested, IsOptional, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { DeliveryAssignmentListRelationFilter } from "../../deliveryAssignment/base/DeliveryAssignmentListRelationFilter";
import { DeliveryComplianceListRelationFilter } from "../../deliveryCompliance/base/DeliveryComplianceListRelationFilter";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { CustomerWhereUniqueInput } from "../../customer/base/CustomerWhereUniqueInput";
import { CustomerListRelationFilter } from "../../customer/base/CustomerListRelationFilter";
import { DeliveryRequestListRelationFilter } from "../../deliveryRequest/base/DeliveryRequestListRelationFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DisputeNoteListRelationFilter } from "../../disputeNote/base/DisputeNoteListRelationFilter";
import { DriverWhereUniqueInput } from "../../driver/base/DriverWhereUniqueInput";
import { DriverListRelationFilter } from "../../driver/base/DriverListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { EvidenceExportListRelationFilter } from "../../evidenceExport/base/EvidenceExportListRelationFilter";
import { BooleanFilter } from "../../util/BooleanFilter";
import { NotificationEventListRelationFilter } from "../../notificationEvent/base/NotificationEventListRelationFilter";
import { EnumUserRoles } from "./EnumUserRoles";
import { ScheduleChangeRequestListRelationFilter } from "../../scheduleChangeRequest/base/ScheduleChangeRequestListRelationFilter";
import { DeliveryStatusHistoryListRelationFilter } from "../../deliveryStatusHistory/base/DeliveryStatusHistoryListRelationFilter";
import { SupportRequestNoteListRelationFilter } from "../../supportRequestNote/base/SupportRequestNoteListRelationFilter";
import { SupportRequestListRelationFilter } from "../../supportRequest/base/SupportRequestListRelationFilter";

@InputType()
class UserWhereInput {
  @ApiProperty({
    required: false,
    type: () => AdminAuditLogListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AdminAuditLogListRelationFilter)
  @IsOptional()
  @Field(() => AdminAuditLogListRelationFilter, {
    nullable: true,
  })
  adminActions?: AdminAuditLogListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => DeliveryAssignmentListRelationFilter,
  })
  @ValidateNested()
  @Type(() => DeliveryAssignmentListRelationFilter)
  @IsOptional()
  @Field(() => DeliveryAssignmentListRelationFilter, {
    nullable: true,
  })
  assignmentsMade?: DeliveryAssignmentListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => AdminAuditLogListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AdminAuditLogListRelationFilter)
  @IsOptional()
  @Field(() => AdminAuditLogListRelationFilter, {
    nullable: true,
  })
  auditTargets?: AdminAuditLogListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => DeliveryComplianceListRelationFilter,
  })
  @ValidateNested()
  @Type(() => DeliveryComplianceListRelationFilter)
  @IsOptional()
  @Field(() => DeliveryComplianceListRelationFilter, {
    nullable: true,
  })
  compliancesVerified?: DeliveryComplianceListRelationFilter;

  @ApiProperty({
    required: false,
    type: DateTimeFilter,
  })
  @Type(() => DateTimeFilter)
  @IsOptional()
  @Field(() => DateTimeFilter, {
    nullable: true,
  })
  createdAt?: DateTimeFilter;

  @ApiProperty({
    required: false,
    type: () => CustomerWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CustomerWhereUniqueInput)
  @IsOptional()
  @Field(() => CustomerWhereUniqueInput, {
    nullable: true,
  })
  customer?: CustomerWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => CustomerListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CustomerListRelationFilter)
  @IsOptional()
  @Field(() => CustomerListRelationFilter, {
    nullable: true,
  })
  customersApproved?: CustomerListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => DeliveryRequestListRelationFilter,
  })
  @ValidateNested()
  @Type(() => DeliveryRequestListRelationFilter)
  @IsOptional()
  @Field(() => DeliveryRequestListRelationFilter, {
    nullable: true,
  })
  deliveriesCreated?: DeliveryRequestListRelationFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  disabledAt?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  disabledReason?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => DisputeNoteListRelationFilter,
  })
  @ValidateNested()
  @Type(() => DisputeNoteListRelationFilter)
  @IsOptional()
  @Field(() => DisputeNoteListRelationFilter, {
    nullable: true,
  })
  disputeNotesAuthored?: DisputeNoteListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => DriverWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DriverWhereUniqueInput)
  @IsOptional()
  @Field(() => DriverWhereUniqueInput, {
    nullable: true,
  })
  driver?: DriverWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => DriverListRelationFilter,
  })
  @ValidateNested()
  @Type(() => DriverListRelationFilter)
  @IsOptional()
  @Field(() => DriverListRelationFilter, {
    nullable: true,
  })
  driversApproved?: DriverListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  email?: StringFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  emailVerifiedAt?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: () => EvidenceExportListRelationFilter,
  })
  @ValidateNested()
  @Type(() => EvidenceExportListRelationFilter)
  @IsOptional()
  @Field(() => EvidenceExportListRelationFilter, {
    nullable: true,
  })
  exportsCreated?: EvidenceExportListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  fullName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: BooleanFilter,
  })
  @Type(() => BooleanFilter)
  @IsOptional()
  @Field(() => BooleanFilter, {
    nullable: true,
  })
  isActive?: BooleanFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  lastLoginAt?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: () => NotificationEventListRelationFilter,
  })
  @ValidateNested()
  @Type(() => NotificationEventListRelationFilter)
  @IsOptional()
  @Field(() => NotificationEventListRelationFilter, {
    nullable: true,
  })
  notifEvents?: NotificationEventListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  password?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  passwordHash?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  phone?: StringNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumUserRoles,
  })
  @IsEnum(EnumUserRoles)
  @IsOptional()
  @Field(() => EnumUserRoles, {
    nullable: true,
  })
  roles?: "PRIVATE_CUSTOMER" | "BUSINESS_CUSTOMER" | "DRIVER" | "ADMIN";

  @ApiProperty({
    required: false,
    type: () => ScheduleChangeRequestListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ScheduleChangeRequestListRelationFilter)
  @IsOptional()
  @Field(() => ScheduleChangeRequestListRelationFilter, {
    nullable: true,
  })
  scheduleChangesDecided?: ScheduleChangeRequestListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ScheduleChangeRequestListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ScheduleChangeRequestListRelationFilter)
  @IsOptional()
  @Field(() => ScheduleChangeRequestListRelationFilter, {
    nullable: true,
  })
  scheduleChangesRequested?: ScheduleChangeRequestListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => DeliveryStatusHistoryListRelationFilter,
  })
  @ValidateNested()
  @Type(() => DeliveryStatusHistoryListRelationFilter)
  @IsOptional()
  @Field(() => DeliveryStatusHistoryListRelationFilter, {
    nullable: true,
  })
  statusActions?: DeliveryStatusHistoryListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => SupportRequestNoteListRelationFilter,
  })
  @ValidateNested()
  @Type(() => SupportRequestNoteListRelationFilter)
  @IsOptional()
  @Field(() => SupportRequestNoteListRelationFilter, {
    nullable: true,
  })
  supportRequestNotesAuthored?: SupportRequestNoteListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => SupportRequestListRelationFilter,
  })
  @ValidateNested()
  @Type(() => SupportRequestListRelationFilter)
  @IsOptional()
  @Field(() => SupportRequestListRelationFilter, {
    nullable: true,
  })
  supportRequestsAssigned?: SupportRequestListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => SupportRequestListRelationFilter,
  })
  @ValidateNested()
  @Type(() => SupportRequestListRelationFilter)
  @IsOptional()
  @Field(() => SupportRequestListRelationFilter, {
    nullable: true,
  })
  supportRequestsRaised?: SupportRequestListRelationFilter;

  @ApiProperty({
    required: false,
    type: DateTimeFilter,
  })
  @Type(() => DateTimeFilter)
  @IsOptional()
  @Field(() => DateTimeFilter, {
    nullable: true,
  })
  updatedAt?: DateTimeFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  username?: StringFilter;
}

export { UserWhereInput as UserWhereInput };
