/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsNumber,
  Max,
  IsOptional,
  IsEnum,
  IsDate,
  IsString,
  ValidateNested,
} from "class-validator";
import { EnumPricingCategoryRuleCategory } from "./EnumPricingCategoryRuleCategory";
import { Type } from "class-transformer";
import { PricingConfig } from "../../pricingConfig/base/PricingConfig";

@ObjectType()
class PricingCategoryRule {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  baseFee!: number | null;

  @ApiProperty({
    required: true,
    enum: EnumPricingCategoryRuleCategory,
  })
  @IsEnum(EnumPricingCategoryRuleCategory)
  @Field(() => EnumPricingCategoryRuleCategory, {
    nullable: true,
  })
  category?: "A" | "B" | "C";

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  flatPrice!: number | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  maxMiles!: number | null;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @Field(() => Number)
  minMiles!: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  perMileRate!: number | null;

  @ApiProperty({
    required: true,
    type: () => PricingConfig,
  })
  @ValidateNested()
  @Type(() => PricingConfig)
  pricingConfig?: PricingConfig;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { PricingCategoryRule as PricingCategoryRule };
