/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { SavedAddressCreateNestedManyWithoutCustomersInput } from "./SavedAddressCreateNestedManyWithoutCustomersInput";
import {
  ValidateNested,
  IsOptional,
  IsEnum,
  IsDate,
  IsString,
  MaxLength,
  IsBoolean,
} from "class-validator";
import { Type } from "class-transformer";
import { EnumCustomerApprovalStatus } from "./EnumCustomerApprovalStatus";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { AdminAuditLogCreateNestedManyWithoutCustomersInput } from "./AdminAuditLogCreateNestedManyWithoutCustomersInput";
import { EnumCustomerCustomerType } from "./EnumCustomerCustomerType";
import { SavedAddressWhereUniqueInput } from "../../savedAddress/base/SavedAddressWhereUniqueInput";
import { DeliveryRequestCreateNestedManyWithoutCustomersInput } from "./DeliveryRequestCreateNestedManyWithoutCustomersInput";
import { NotificationEventCreateNestedManyWithoutCustomersInput } from "./NotificationEventCreateNestedManyWithoutCustomersInput";
import { PricingConfigWhereUniqueInput } from "../../pricingConfig/base/PricingConfigWhereUniqueInput";
import { EnumCustomerPricingModeOverride } from "./EnumCustomerPricingModeOverride";
import { DeliveryRatingCreateNestedManyWithoutCustomersInput } from "./DeliveryRatingCreateNestedManyWithoutCustomersInput";
import { SavedVehicleCreateNestedManyWithoutCustomersInput } from "./SavedVehicleCreateNestedManyWithoutCustomersInput";

@InputType()
class CustomerCreateInput {
  @ApiProperty({
    required: false,
    type: () => SavedAddressCreateNestedManyWithoutCustomersInput,
  })
  @ValidateNested()
  @Type(() => SavedAddressCreateNestedManyWithoutCustomersInput)
  @IsOptional()
  @Field(() => SavedAddressCreateNestedManyWithoutCustomersInput, {
    nullable: true,
  })
  addresses?: SavedAddressCreateNestedManyWithoutCustomersInput;

  @ApiProperty({
    required: true,
    enum: EnumCustomerApprovalStatus,
  })
  @IsEnum(EnumCustomerApprovalStatus)
  @Field(() => EnumCustomerApprovalStatus)
  approvalStatus!: "PENDING" | "APPROVED" | "REJECTED" | "SUSPENDED";

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  approvedAt?: Date | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  approvedBy?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => AdminAuditLogCreateNestedManyWithoutCustomersInput,
  })
  @ValidateNested()
  @Type(() => AdminAuditLogCreateNestedManyWithoutCustomersInput)
  @IsOptional()
  @Field(() => AdminAuditLogCreateNestedManyWithoutCustomersInput, {
    nullable: true,
  })
  audits?: AdminAuditLogCreateNestedManyWithoutCustomersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  businessAddress?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  businessName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  businessPhone?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  businessPlaceId?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  businessWebsite?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  contactEmail?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  contactName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  contactPhone?: string | null;

  @ApiProperty({
    required: true,
    enum: EnumCustomerCustomerType,
  })
  @IsEnum(EnumCustomerCustomerType)
  @Field(() => EnumCustomerCustomerType)
  customerType!: "BUSINESS" | "PRIVATE";

  @ApiProperty({
    required: false,
    type: () => SavedAddressWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SavedAddressWhereUniqueInput)
  @IsOptional()
  @Field(() => SavedAddressWhereUniqueInput, {
    nullable: true,
  })
  defaultPickup?: SavedAddressWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => DeliveryRequestCreateNestedManyWithoutCustomersInput,
  })
  @ValidateNested()
  @Type(() => DeliveryRequestCreateNestedManyWithoutCustomersInput)
  @IsOptional()
  @Field(() => DeliveryRequestCreateNestedManyWithoutCustomersInput, {
    nullable: true,
  })
  deliveries?: DeliveryRequestCreateNestedManyWithoutCustomersInput;

  @ApiProperty({
    required: false,
    type: () => NotificationEventCreateNestedManyWithoutCustomersInput,
  })
  @ValidateNested()
  @Type(() => NotificationEventCreateNestedManyWithoutCustomersInput)
  @IsOptional()
  @Field(() => NotificationEventCreateNestedManyWithoutCustomersInput, {
    nullable: true,
  })
  notifications?: NotificationEventCreateNestedManyWithoutCustomersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone?: string | null;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  postpaidEnabled!: boolean;

  @ApiProperty({
    required: false,
    type: () => PricingConfigWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PricingConfigWhereUniqueInput)
  @IsOptional()
  @Field(() => PricingConfigWhereUniqueInput, {
    nullable: true,
  })
  pricingConfig?: PricingConfigWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    enum: EnumCustomerPricingModeOverride,
  })
  @IsEnum(EnumCustomerPricingModeOverride)
  @IsOptional()
  @Field(() => EnumCustomerPricingModeOverride, {
    nullable: true,
  })
  pricingModeOverride?: "PER_MILE" | "FLAT_TIER" | "CATEGORY_ABC" | null;

  @ApiProperty({
    required: false,
    type: () => DeliveryRatingCreateNestedManyWithoutCustomersInput,
  })
  @ValidateNested()
  @Type(() => DeliveryRatingCreateNestedManyWithoutCustomersInput)
  @IsOptional()
  @Field(() => DeliveryRatingCreateNestedManyWithoutCustomersInput, {
    nullable: true,
  })
  ratings?: DeliveryRatingCreateNestedManyWithoutCustomersInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  suspendedAt?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  suspensionReason?: string | null;

  @ApiProperty({
    required: true,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @Field(() => UserWhereUniqueInput)
  user!: UserWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => SavedVehicleCreateNestedManyWithoutCustomersInput,
  })
  @ValidateNested()
  @Type(() => SavedVehicleCreateNestedManyWithoutCustomersInput)
  @IsOptional()
  @Field(() => SavedVehicleCreateNestedManyWithoutCustomersInput, {
    nullable: true,
  })
  vehicles?: SavedVehicleCreateNestedManyWithoutCustomersInput;
}

export { CustomerCreateInput as CustomerCreateInput };
