/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Customer as PrismaCustomer,
  SavedAddress as PrismaSavedAddress,
  AdminAuditLog as PrismaAdminAuditLog,
  DeliveryRequest as PrismaDeliveryRequest,
  NotificationEvent as PrismaNotificationEvent,
  DeliveryRating as PrismaDeliveryRating,
  SavedVehicle as PrismaSavedVehicle,
  User as PrismaUser,
  PricingConfig as PrismaPricingConfig,
} from "@prisma/client";

export class CustomerServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.CustomerCountArgs, "select">): Promise<number> {
    return this.prisma.customer.count(args);
  }

  async customers(
    args: Prisma.CustomerFindManyArgs
  ): Promise<PrismaCustomer[]> {
    return this.prisma.customer.findMany(args);
  }
  async customer(
    args: Prisma.CustomerFindUniqueArgs
  ): Promise<PrismaCustomer | null> {
    return this.prisma.customer.findUnique(args);
  }
  async createCustomer(
    args: Prisma.CustomerCreateArgs
  ): Promise<PrismaCustomer> {
    return this.prisma.customer.create(args);
  }
  async updateCustomer(
    args: Prisma.CustomerUpdateArgs
  ): Promise<PrismaCustomer> {
    return this.prisma.customer.update(args);
  }
  async deleteCustomer(
    args: Prisma.CustomerDeleteArgs
  ): Promise<PrismaCustomer> {
    return this.prisma.customer.delete(args);
  }

  async findAddresses(
    parentId: string,
    args: Prisma.SavedAddressFindManyArgs
  ): Promise<PrismaSavedAddress[]> {
    return this.prisma.customer
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .addresses(args);
  }

  async findAudits(
    parentId: string,
    args: Prisma.AdminAuditLogFindManyArgs
  ): Promise<PrismaAdminAuditLog[]> {
    return this.prisma.customer
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .audits(args);
  }

  async findDeliveries(
    parentId: string,
    args: Prisma.DeliveryRequestFindManyArgs
  ): Promise<PrismaDeliveryRequest[]> {
    return this.prisma.customer
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .deliveries(args);
  }

  async findNotifications(
    parentId: string,
    args: Prisma.NotificationEventFindManyArgs
  ): Promise<PrismaNotificationEvent[]> {
    return this.prisma.customer
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .notifications(args);
  }

  async findRatings(
    parentId: string,
    args: Prisma.DeliveryRatingFindManyArgs
  ): Promise<PrismaDeliveryRating[]> {
    return this.prisma.customer
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .ratings(args);
  }

  async findVehicles(
    parentId: string,
    args: Prisma.SavedVehicleFindManyArgs
  ): Promise<PrismaSavedVehicle[]> {
    return this.prisma.customer
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .vehicles(args);
  }

  async getApprovedBy(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.customer
      .findUnique({
        where: { id: parentId },
      })
      .approvedBy();
  }

  async getDefaultPickup(parentId: string): Promise<PrismaSavedAddress | null> {
    return this.prisma.customer
      .findUnique({
        where: { id: parentId },
      })
      .defaultPickup();
  }

  async getPricingConfig(
    parentId: string
  ): Promise<PrismaPricingConfig | null> {
    return this.prisma.customer
      .findUnique({
        where: { id: parentId },
      })
      .pricingConfig();
  }

  async getUser(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.customer
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
