/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsBoolean,
  IsInt,
  Max,
  IsDate,
  IsEnum,
  IsString,
  IsNumber,
  IsOptional,
  MaxLength,
} from "class-validator";

import { Type } from "class-transformer";
import { EnumSchedulingPolicyCustomerType } from "./EnumSchedulingPolicyCustomerType";
import { EnumSchedulingPolicyDefaultMode } from "./EnumSchedulingPolicyDefaultMode";
import { EnumSchedulingPolicyServiceType } from "./EnumSchedulingPolicyServiceType";

@ObjectType()
class SchedulingPolicy {
  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  active!: boolean;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  afterHoursEnabled!: boolean;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @Field(() => Number)
  bufferMinutes!: number;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
    enum: EnumSchedulingPolicyCustomerType,
  })
  @IsEnum(EnumSchedulingPolicyCustomerType)
  @Field(() => EnumSchedulingPolicyCustomerType, {
    nullable: true,
  })
  customerType?: "BUSINESS" | "PRIVATE";

  @ApiProperty({
    required: true,
    enum: EnumSchedulingPolicyDefaultMode,
  })
  @IsEnum(EnumSchedulingPolicyDefaultMode)
  @Field(() => EnumSchedulingPolicyDefaultMode, {
    nullable: true,
  })
  defaultMode?: "SAME_DAY" | "NEXT_DAY";

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  maxSameDayMiles!: number | null;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  requiresOpsConfirmation!: boolean;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  sameDayCutoffTime!: string | null;

  @ApiProperty({
    required: false,
    enum: EnumSchedulingPolicyServiceType,
  })
  @IsEnum(EnumSchedulingPolicyServiceType)
  @IsOptional()
  @Field(() => EnumSchedulingPolicyServiceType, {
    nullable: true,
  })
  serviceType?:
    | "HOME_DELIVERY"
    | "BETWEEN_LOCATIONS"
    | "SERVICE_PICKUP_RETURN"
    | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { SchedulingPolicy as SchedulingPolicy };
