/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  SchedulingPolicy as PrismaSchedulingPolicy,
} from "@prisma/client";

export class SchedulingPolicyServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.SchedulingPolicyCountArgs, "select">
  ): Promise<number> {
    return this.prisma.schedulingPolicy.count(args);
  }

  async schedulingPolicies(
    args: Prisma.SchedulingPolicyFindManyArgs
  ): Promise<PrismaSchedulingPolicy[]> {
    return this.prisma.schedulingPolicy.findMany(args);
  }
  async schedulingPolicy(
    args: Prisma.SchedulingPolicyFindUniqueArgs
  ): Promise<PrismaSchedulingPolicy | null> {
    return this.prisma.schedulingPolicy.findUnique(args);
  }
  async createSchedulingPolicy(
    args: Prisma.SchedulingPolicyCreateArgs
  ): Promise<PrismaSchedulingPolicy> {
    return this.prisma.schedulingPolicy.create(args);
  }
  async updateSchedulingPolicy(
    args: Prisma.SchedulingPolicyUpdateArgs
  ): Promise<PrismaSchedulingPolicy> {
    return this.prisma.schedulingPolicy.update(args);
  }
  async deleteSchedulingPolicy(
    args: Prisma.SchedulingPolicyDeleteArgs
  ): Promise<PrismaSchedulingPolicy> {
    return this.prisma.schedulingPolicy.delete(args);
  }
}
