/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SchedulingPolicyService } from "../schedulingPolicy.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SchedulingPolicyCreateInput } from "./SchedulingPolicyCreateInput";
import { SchedulingPolicy } from "./SchedulingPolicy";
import { SchedulingPolicyFindManyArgs } from "./SchedulingPolicyFindManyArgs";
import { SchedulingPolicyWhereUniqueInput } from "./SchedulingPolicyWhereUniqueInput";
import { SchedulingPolicyUpdateInput } from "./SchedulingPolicyUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SchedulingPolicyControllerBase {
  constructor(
    protected readonly service: SchedulingPolicyService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SchedulingPolicy })
  @nestAccessControl.UseRoles({
    resource: "SchedulingPolicy",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSchedulingPolicy(
    @common.Body() data: SchedulingPolicyCreateInput
  ): Promise<SchedulingPolicy> {
    return await this.service.createSchedulingPolicy({
      data: data,
      select: {
        active: true,
        afterHoursEnabled: true,
        bufferMinutes: true,
        createdAt: true,
        customerType: true,
        defaultMode: true,
        id: true,
        maxSameDayMiles: true,
        requiresOpsConfirmation: true,
        sameDayCutoffTime: true,
        serviceType: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [SchedulingPolicy] })
  @ApiNestedQuery(SchedulingPolicyFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SchedulingPolicy",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async schedulingPolicies(
    @common.Req() request: Request
  ): Promise<SchedulingPolicy[]> {
    const args = plainToClass(SchedulingPolicyFindManyArgs, request.query);
    return this.service.schedulingPolicies({
      ...args,
      select: {
        active: true,
        afterHoursEnabled: true,
        bufferMinutes: true,
        createdAt: true,
        customerType: true,
        defaultMode: true,
        id: true,
        maxSameDayMiles: true,
        requiresOpsConfirmation: true,
        sameDayCutoffTime: true,
        serviceType: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SchedulingPolicy })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SchedulingPolicy",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async schedulingPolicy(
    @common.Param() params: SchedulingPolicyWhereUniqueInput
  ): Promise<SchedulingPolicy | null> {
    const result = await this.service.schedulingPolicy({
      where: params,
      select: {
        active: true,
        afterHoursEnabled: true,
        bufferMinutes: true,
        createdAt: true,
        customerType: true,
        defaultMode: true,
        id: true,
        maxSameDayMiles: true,
        requiresOpsConfirmation: true,
        sameDayCutoffTime: true,
        serviceType: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SchedulingPolicy })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SchedulingPolicy",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSchedulingPolicy(
    @common.Param() params: SchedulingPolicyWhereUniqueInput,
    @common.Body() data: SchedulingPolicyUpdateInput
  ): Promise<SchedulingPolicy | null> {
    try {
      return await this.service.updateSchedulingPolicy({
        where: params,
        data: data,
        select: {
          active: true,
          afterHoursEnabled: true,
          bufferMinutes: true,
          createdAt: true,
          customerType: true,
          defaultMode: true,
          id: true,
          maxSameDayMiles: true,
          requiresOpsConfirmation: true,
          sameDayCutoffTime: true,
          serviceType: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SchedulingPolicy })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SchedulingPolicy",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSchedulingPolicy(
    @common.Param() params: SchedulingPolicyWhereUniqueInput
  ): Promise<SchedulingPolicy | null> {
    try {
      return await this.service.deleteSchedulingPolicy({
        where: params,
        select: {
          active: true,
          afterHoursEnabled: true,
          bufferMinutes: true,
          createdAt: true,
          customerType: true,
          defaultMode: true,
          id: true,
          maxSameDayMiles: true,
          requiresOpsConfirmation: true,
          sameDayCutoffTime: true,
          serviceType: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
