/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsBoolean,
  IsOptional,
  IsInt,
  Max,
  IsEnum,
  IsNumber,
  IsString,
  MaxLength,
} from "class-validator";
import { EnumSchedulingPolicyCustomerType } from "./EnumSchedulingPolicyCustomerType";
import { EnumSchedulingPolicyDefaultMode } from "./EnumSchedulingPolicyDefaultMode";
import { EnumSchedulingPolicyServiceType } from "./EnumSchedulingPolicyServiceType";

@InputType()
class SchedulingPolicyUpdateInput {
  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  active?: boolean;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  afterHoursEnabled?: boolean;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  bufferMinutes?: number;

  @ApiProperty({
    required: false,
    enum: EnumSchedulingPolicyCustomerType,
  })
  @IsEnum(EnumSchedulingPolicyCustomerType)
  @IsOptional()
  @Field(() => EnumSchedulingPolicyCustomerType, {
    nullable: true,
  })
  customerType?: "BUSINESS" | "PRIVATE";

  @ApiProperty({
    required: false,
    enum: EnumSchedulingPolicyDefaultMode,
  })
  @IsEnum(EnumSchedulingPolicyDefaultMode)
  @IsOptional()
  @Field(() => EnumSchedulingPolicyDefaultMode, {
    nullable: true,
  })
  defaultMode?: "SAME_DAY" | "NEXT_DAY";

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  maxSameDayMiles?: number | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  requiresOpsConfirmation?: boolean;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  sameDayCutoffTime?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumSchedulingPolicyServiceType,
  })
  @IsEnum(EnumSchedulingPolicyServiceType)
  @IsOptional()
  @Field(() => EnumSchedulingPolicyServiceType, {
    nullable: true,
  })
  serviceType?:
    | "HOME_DELIVERY"
    | "BETWEEN_LOCATIONS"
    | "SERVICE_PICKUP_RETURN"
    | null;
}

export { SchedulingPolicyUpdateInput as SchedulingPolicyUpdateInput };
