/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  DisputeCase as PrismaDisputeCase,
  DisputeNote as PrismaDisputeNote,
  DeliveryRequest as PrismaDeliveryRequest,
} from "@prisma/client";

export class DisputeCaseServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.DisputeCaseCountArgs, "select">
  ): Promise<number> {
    return this.prisma.disputeCase.count(args);
  }

  async disputeCases(
    args: Prisma.DisputeCaseFindManyArgs
  ): Promise<PrismaDisputeCase[]> {
    return this.prisma.disputeCase.findMany(args);
  }
  async disputeCase(
    args: Prisma.DisputeCaseFindUniqueArgs
  ): Promise<PrismaDisputeCase | null> {
    return this.prisma.disputeCase.findUnique(args);
  }
  async createDisputeCase(
    args: Prisma.DisputeCaseCreateArgs
  ): Promise<PrismaDisputeCase> {
    return this.prisma.disputeCase.create(args);
  }
  async updateDisputeCase(
    args: Prisma.DisputeCaseUpdateArgs
  ): Promise<PrismaDisputeCase> {
    return this.prisma.disputeCase.update(args);
  }
  async deleteDisputeCase(
    args: Prisma.DisputeCaseDeleteArgs
  ): Promise<PrismaDisputeCase> {
    return this.prisma.disputeCase.delete(args);
  }

  async findNotes(
    parentId: string,
    args: Prisma.DisputeNoteFindManyArgs
  ): Promise<PrismaDisputeNote[]> {
    return this.prisma.disputeCase
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .notes(args);
  }

  async getDelivery(parentId: string): Promise<PrismaDeliveryRequest | null> {
    return this.prisma.disputeCase
      .findUnique({
        where: { id: parentId },
      })
      .delivery();
  }
}
