/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DisputeCaseService } from "../disputeCase.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DisputeCaseCreateInput } from "./DisputeCaseCreateInput";
import { DisputeCase } from "./DisputeCase";
import { DisputeCaseFindManyArgs } from "./DisputeCaseFindManyArgs";
import { DisputeCaseWhereUniqueInput } from "./DisputeCaseWhereUniqueInput";
import { DisputeCaseUpdateInput } from "./DisputeCaseUpdateInput";
import { DisputeNoteFindManyArgs } from "../../disputeNote/base/DisputeNoteFindManyArgs";
import { DisputeNote } from "../../disputeNote/base/DisputeNote";
import { DisputeNoteWhereUniqueInput } from "../../disputeNote/base/DisputeNoteWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DisputeCaseControllerBase {
  constructor(
    protected readonly service: DisputeCaseService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DisputeCase })
  @nestAccessControl.UseRoles({
    resource: "DisputeCase",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDisputeCase(
    @common.Body() data: DisputeCaseCreateInput
  ): Promise<DisputeCase> {
    return await this.service.createDisputeCase({
      data: {
        ...data,

        delivery: {
          connect: data.delivery,
        },
      },
      select: {
        closedAt: true,
        createdAt: true,

        delivery: {
          select: {
            id: true,
          },
        },

        id: true,
        legalHold: true,
        openedAt: true,
        reason: true,
        resolvedAt: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DisputeCase] })
  @ApiNestedQuery(DisputeCaseFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DisputeCase",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async disputeCases(@common.Req() request: Request): Promise<DisputeCase[]> {
    const args = plainToClass(DisputeCaseFindManyArgs, request.query);
    return this.service.disputeCases({
      ...args,
      select: {
        closedAt: true,
        createdAt: true,

        delivery: {
          select: {
            id: true,
          },
        },

        id: true,
        legalHold: true,
        openedAt: true,
        reason: true,
        resolvedAt: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DisputeCase })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DisputeCase",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async disputeCase(
    @common.Param() params: DisputeCaseWhereUniqueInput
  ): Promise<DisputeCase | null> {
    const result = await this.service.disputeCase({
      where: params,
      select: {
        closedAt: true,
        createdAt: true,

        delivery: {
          select: {
            id: true,
          },
        },

        id: true,
        legalHold: true,
        openedAt: true,
        reason: true,
        resolvedAt: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DisputeCase })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DisputeCase",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDisputeCase(
    @common.Param() params: DisputeCaseWhereUniqueInput,
    @common.Body() data: DisputeCaseUpdateInput
  ): Promise<DisputeCase | null> {
    try {
      return await this.service.updateDisputeCase({
        where: params,
        data: {
          ...data,

          delivery: {
            connect: data.delivery,
          },
        },
        select: {
          closedAt: true,
          createdAt: true,

          delivery: {
            select: {
              id: true,
            },
          },

          id: true,
          legalHold: true,
          openedAt: true,
          reason: true,
          resolvedAt: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DisputeCase })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DisputeCase",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDisputeCase(
    @common.Param() params: DisputeCaseWhereUniqueInput
  ): Promise<DisputeCase | null> {
    try {
      return await this.service.deleteDisputeCase({
        where: params,
        select: {
          closedAt: true,
          createdAt: true,

          delivery: {
            select: {
              id: true,
            },
          },

          id: true,
          legalHold: true,
          openedAt: true,
          reason: true,
          resolvedAt: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/notes")
  @ApiNestedQuery(DisputeNoteFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DisputeNote",
    action: "read",
    possession: "any",
  })
  async findNotes(
    @common.Req() request: Request,
    @common.Param() params: DisputeCaseWhereUniqueInput
  ): Promise<DisputeNote[]> {
    const query = plainToClass(DisputeNoteFindManyArgs, request.query);
    const results = await this.service.findNotes(params.id, {
      ...query,
      select: {
        author: {
          select: {
            id: true,
          },
        },

        createdAt: true,

        dispute: {
          select: {
            id: true,
          },
        },

        id: true,
        note: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/notes")
  @nestAccessControl.UseRoles({
    resource: "DisputeCase",
    action: "update",
    possession: "any",
  })
  async connectNotes(
    @common.Param() params: DisputeCaseWhereUniqueInput,
    @common.Body() body: DisputeNoteWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      notes: {
        connect: body,
      },
    };
    await this.service.updateDisputeCase({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/notes")
  @nestAccessControl.UseRoles({
    resource: "DisputeCase",
    action: "update",
    possession: "any",
  })
  async updateNotes(
    @common.Param() params: DisputeCaseWhereUniqueInput,
    @common.Body() body: DisputeNoteWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      notes: {
        set: body,
      },
    };
    await this.service.updateDisputeCase({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/notes")
  @nestAccessControl.UseRoles({
    resource: "DisputeCase",
    action: "update",
    possession: "any",
  })
  async disconnectNotes(
    @common.Param() params: DisputeCaseWhereUniqueInput,
    @common.Body() body: DisputeNoteWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      notes: {
        disconnect: body,
      },
    };
    await this.service.updateDisputeCase({
      where: params,
      data,
      select: { id: true },
    });
  }
}
