/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { DisputeCase } from "./DisputeCase";
import { DisputeCaseCountArgs } from "./DisputeCaseCountArgs";
import { DisputeCaseFindManyArgs } from "./DisputeCaseFindManyArgs";
import { DisputeCaseFindUniqueArgs } from "./DisputeCaseFindUniqueArgs";
import { CreateDisputeCaseArgs } from "./CreateDisputeCaseArgs";
import { UpdateDisputeCaseArgs } from "./UpdateDisputeCaseArgs";
import { DeleteDisputeCaseArgs } from "./DeleteDisputeCaseArgs";
import { DisputeNoteFindManyArgs } from "../../disputeNote/base/DisputeNoteFindManyArgs";
import { DisputeNote } from "../../disputeNote/base/DisputeNote";
import { DeliveryRequest } from "../../deliveryRequest/base/DeliveryRequest";
import { DisputeCaseService } from "../disputeCase.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => DisputeCase)
export class DisputeCaseResolverBase {
  constructor(
    protected readonly service: DisputeCaseService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "DisputeCase",
    action: "read",
    possession: "any",
  })
  async _disputeCasesMeta(
    @graphql.Args() args: DisputeCaseCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [DisputeCase])
  @nestAccessControl.UseRoles({
    resource: "DisputeCase",
    action: "read",
    possession: "any",
  })
  async disputeCases(
    @graphql.Args() args: DisputeCaseFindManyArgs
  ): Promise<DisputeCase[]> {
    return this.service.disputeCases(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => DisputeCase, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "DisputeCase",
    action: "read",
    possession: "own",
  })
  async disputeCase(
    @graphql.Args() args: DisputeCaseFindUniqueArgs
  ): Promise<DisputeCase | null> {
    const result = await this.service.disputeCase(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => DisputeCase)
  @nestAccessControl.UseRoles({
    resource: "DisputeCase",
    action: "create",
    possession: "any",
  })
  async createDisputeCase(
    @graphql.Args() args: CreateDisputeCaseArgs
  ): Promise<DisputeCase> {
    return await this.service.createDisputeCase({
      ...args,
      data: {
        ...args.data,

        delivery: {
          connect: args.data.delivery,
        },
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => DisputeCase)
  @nestAccessControl.UseRoles({
    resource: "DisputeCase",
    action: "update",
    possession: "any",
  })
  async updateDisputeCase(
    @graphql.Args() args: UpdateDisputeCaseArgs
  ): Promise<DisputeCase | null> {
    try {
      return await this.service.updateDisputeCase({
        ...args,
        data: {
          ...args.data,

          delivery: {
            connect: args.data.delivery,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => DisputeCase)
  @nestAccessControl.UseRoles({
    resource: "DisputeCase",
    action: "delete",
    possession: "any",
  })
  async deleteDisputeCase(
    @graphql.Args() args: DeleteDisputeCaseArgs
  ): Promise<DisputeCase | null> {
    try {
      return await this.service.deleteDisputeCase(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [DisputeNote], { name: "notes" })
  @nestAccessControl.UseRoles({
    resource: "DisputeNote",
    action: "read",
    possession: "any",
  })
  async findNotes(
    @graphql.Parent() parent: DisputeCase,
    @graphql.Args() args: DisputeNoteFindManyArgs
  ): Promise<DisputeNote[]> {
    const results = await this.service.findNotes(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => DeliveryRequest, {
    nullable: true,
    name: "delivery",
  })
  @nestAccessControl.UseRoles({
    resource: "DeliveryRequest",
    action: "read",
    possession: "any",
  })
  async getDelivery(
    @graphql.Parent() parent: DisputeCase
  ): Promise<DeliveryRequest | null> {
    const result = await this.service.getDelivery(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
