/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  IsOptional,
  ValidateNested,
  IsBoolean,
  IsString,
  MaxLength,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { DeliveryRequestWhereUniqueInput } from "../../deliveryRequest/base/DeliveryRequestWhereUniqueInput";
import { DisputeNoteUpdateManyWithoutDisputeCasesInput } from "./DisputeNoteUpdateManyWithoutDisputeCasesInput";
import { EnumDisputeCaseStatus } from "./EnumDisputeCaseStatus";

@InputType()
class DisputeCaseUpdateInput {
  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  closedAt?: Date | null;

  @ApiProperty({
    required: false,
    type: () => DeliveryRequestWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DeliveryRequestWhereUniqueInput)
  @IsOptional()
  @Field(() => DeliveryRequestWhereUniqueInput, {
    nullable: true,
  })
  delivery?: DeliveryRequestWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  legalHold?: boolean;

  @ApiProperty({
    required: false,
    type: () => DisputeNoteUpdateManyWithoutDisputeCasesInput,
  })
  @ValidateNested()
  @Type(() => DisputeNoteUpdateManyWithoutDisputeCasesInput)
  @IsOptional()
  @Field(() => DisputeNoteUpdateManyWithoutDisputeCasesInput, {
    nullable: true,
  })
  notes?: DisputeNoteUpdateManyWithoutDisputeCasesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  reason?: string;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  resolvedAt?: Date | null;

  @ApiProperty({
    required: false,
    enum: EnumDisputeCaseStatus,
  })
  @IsEnum(EnumDisputeCaseStatus)
  @IsOptional()
  @Field(() => EnumDisputeCaseStatus, {
    nullable: true,
  })
  status?: "OPEN" | "UNDER_REVIEW" | "RESOLVED" | "CLOSED";
}

export { DisputeCaseUpdateInput as DisputeCaseUpdateInput };
