/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested, IsEnum } from "class-validator";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DeliveryRequestWhereUniqueInput } from "../../deliveryRequest/base/DeliveryRequestWhereUniqueInput";
import { StringFilter } from "../../util/StringFilter";
import { EnumScheduleChangeRequestRequestedByRole } from "./EnumScheduleChangeRequestRequestedByRole";
import { EnumScheduleChangeRequestStatus } from "./EnumScheduleChangeRequestStatus";

@InputType()
class ScheduleChangeRequestWhereInput {
  @ApiProperty({
    required: false,
    type: DateTimeFilter,
  })
  @Type(() => DateTimeFilter)
  @IsOptional()
  @Field(() => DateTimeFilter, {
    nullable: true,
  })
  createdAt?: DateTimeFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  decidedAt?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  decidedBy?: UserWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  decisionNote?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => DeliveryRequestWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DeliveryRequestWhereUniqueInput)
  @IsOptional()
  @Field(() => DeliveryRequestWhereUniqueInput, {
    nullable: true,
  })
  delivery?: DeliveryRequestWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  proposedDropoffWindowEnd?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  proposedDropoffWindowStart?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  proposedPickupWindowEnd?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  proposedPickupWindowStart?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  reason?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  requestedBy?: UserWhereUniqueInput;

  @ApiProperty({
    required: false,
    enum: EnumScheduleChangeRequestRequestedByRole,
  })
  @IsEnum(EnumScheduleChangeRequestRequestedByRole)
  @IsOptional()
  @Field(() => EnumScheduleChangeRequestRequestedByRole, {
    nullable: true,
  })
  requestedByRole?:
    | "PRIVATE_CUSTOMER"
    | "BUSINESS_CUSTOMER"
    | "DRIVER"
    | "ADMIN";

  @ApiProperty({
    required: false,
    enum: EnumScheduleChangeRequestStatus,
  })
  @IsEnum(EnumScheduleChangeRequestStatus)
  @IsOptional()
  @Field(() => EnumScheduleChangeRequestStatus, {
    nullable: true,
  })
  status?: "PENDING" | "APPROVED" | "DECLINED" | "CANCELLED";

  @ApiProperty({
    required: false,
    type: DateTimeFilter,
  })
  @Type(() => DateTimeFilter)
  @IsOptional()
  @Field(() => DateTimeFilter, {
    nullable: true,
  })
  updatedAt?: DateTimeFilter;
}

export { ScheduleChangeRequestWhereInput as ScheduleChangeRequestWhereInput };
