/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  IsOptional,
  ValidateNested,
  IsString,
  MaxLength,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { DeliveryRequestWhereUniqueInput } from "../../deliveryRequest/base/DeliveryRequestWhereUniqueInput";
import { EnumScheduleChangeRequestRequestedByRole } from "./EnumScheduleChangeRequestRequestedByRole";
import { EnumScheduleChangeRequestStatus } from "./EnumScheduleChangeRequestStatus";

@InputType()
class ScheduleChangeRequestCreateInput {
  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  decidedAt?: Date | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  decidedBy?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  decisionNote?: string | null;

  @ApiProperty({
    required: true,
    type: () => DeliveryRequestWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DeliveryRequestWhereUniqueInput)
  @Field(() => DeliveryRequestWhereUniqueInput)
  delivery!: DeliveryRequestWhereUniqueInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  proposedDropoffWindowEnd?: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  proposedDropoffWindowStart?: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  proposedPickupWindowEnd?: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  proposedPickupWindowStart?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  reason?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  requestedBy?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    enum: EnumScheduleChangeRequestRequestedByRole,
  })
  @IsEnum(EnumScheduleChangeRequestRequestedByRole)
  @IsOptional()
  @Field(() => EnumScheduleChangeRequestRequestedByRole, {
    nullable: true,
  })
  requestedByRole?:
    | "PRIVATE_CUSTOMER"
    | "BUSINESS_CUSTOMER"
    | "DRIVER"
    | "ADMIN"
    | null;

  @ApiProperty({
    required: true,
    enum: EnumScheduleChangeRequestStatus,
  })
  @IsEnum(EnumScheduleChangeRequestStatus)
  @Field(() => EnumScheduleChangeRequestStatus)
  status!: "PENDING" | "APPROVED" | "DECLINED" | "CANCELLED";
}

export { ScheduleChangeRequestCreateInput as ScheduleChangeRequestCreateInput };
