/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { ScheduleChangeRequest } from "./ScheduleChangeRequest";
import { ScheduleChangeRequestCountArgs } from "./ScheduleChangeRequestCountArgs";
import { ScheduleChangeRequestFindManyArgs } from "./ScheduleChangeRequestFindManyArgs";
import { ScheduleChangeRequestFindUniqueArgs } from "./ScheduleChangeRequestFindUniqueArgs";
import { CreateScheduleChangeRequestArgs } from "./CreateScheduleChangeRequestArgs";
import { UpdateScheduleChangeRequestArgs } from "./UpdateScheduleChangeRequestArgs";
import { DeleteScheduleChangeRequestArgs } from "./DeleteScheduleChangeRequestArgs";
import { User } from "../../user/base/User";
import { DeliveryRequest } from "../../deliveryRequest/base/DeliveryRequest";
import { ScheduleChangeRequestService } from "../scheduleChangeRequest.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ScheduleChangeRequest)
export class ScheduleChangeRequestResolverBase {
  constructor(
    protected readonly service: ScheduleChangeRequestService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ScheduleChangeRequest",
    action: "read",
    possession: "any",
  })
  async _scheduleChangeRequestsMeta(
    @graphql.Args() args: ScheduleChangeRequestCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ScheduleChangeRequest])
  @nestAccessControl.UseRoles({
    resource: "ScheduleChangeRequest",
    action: "read",
    possession: "any",
  })
  async scheduleChangeRequests(
    @graphql.Args() args: ScheduleChangeRequestFindManyArgs
  ): Promise<ScheduleChangeRequest[]> {
    return this.service.scheduleChangeRequests(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ScheduleChangeRequest, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ScheduleChangeRequest",
    action: "read",
    possession: "own",
  })
  async scheduleChangeRequest(
    @graphql.Args() args: ScheduleChangeRequestFindUniqueArgs
  ): Promise<ScheduleChangeRequest | null> {
    const result = await this.service.scheduleChangeRequest(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ScheduleChangeRequest)
  @nestAccessControl.UseRoles({
    resource: "ScheduleChangeRequest",
    action: "create",
    possession: "any",
  })
  async createScheduleChangeRequest(
    @graphql.Args() args: CreateScheduleChangeRequestArgs
  ): Promise<ScheduleChangeRequest> {
    return await this.service.createScheduleChangeRequest({
      ...args,
      data: {
        ...args.data,

        decidedBy: args.data.decidedBy
          ? {
              connect: args.data.decidedBy,
            }
          : undefined,

        delivery: {
          connect: args.data.delivery,
        },

        requestedBy: args.data.requestedBy
          ? {
              connect: args.data.requestedBy,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ScheduleChangeRequest)
  @nestAccessControl.UseRoles({
    resource: "ScheduleChangeRequest",
    action: "update",
    possession: "any",
  })
  async updateScheduleChangeRequest(
    @graphql.Args() args: UpdateScheduleChangeRequestArgs
  ): Promise<ScheduleChangeRequest | null> {
    try {
      return await this.service.updateScheduleChangeRequest({
        ...args,
        data: {
          ...args.data,

          decidedBy: args.data.decidedBy
            ? {
                connect: args.data.decidedBy,
              }
            : undefined,

          delivery: {
            connect: args.data.delivery,
          },

          requestedBy: args.data.requestedBy
            ? {
                connect: args.data.requestedBy,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ScheduleChangeRequest)
  @nestAccessControl.UseRoles({
    resource: "ScheduleChangeRequest",
    action: "delete",
    possession: "any",
  })
  async deleteScheduleChangeRequest(
    @graphql.Args() args: DeleteScheduleChangeRequestArgs
  ): Promise<ScheduleChangeRequest | null> {
    try {
      return await this.service.deleteScheduleChangeRequest(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "decidedBy",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getDecidedBy(
    @graphql.Parent() parent: ScheduleChangeRequest
  ): Promise<User | null> {
    const result = await this.service.getDecidedBy(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => DeliveryRequest, {
    nullable: true,
    name: "delivery",
  })
  @nestAccessControl.UseRoles({
    resource: "DeliveryRequest",
    action: "read",
    possession: "any",
  })
  async getDelivery(
    @graphql.Parent() parent: ScheduleChangeRequest
  ): Promise<DeliveryRequest | null> {
    const result = await this.service.getDelivery(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "requestedBy",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getRequestedBy(
    @graphql.Parent() parent: ScheduleChangeRequest
  ): Promise<User | null> {
    const result = await this.service.getRequestedBy(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
