/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsNumber,
  Max,
  IsOptional,
  IsDate,
  ValidateNested,
  IsString,
  MaxLength,
  IsEnum,
} from "class-validator";

import { Type } from "class-transformer";
import { DeliveryRequestWhereUniqueInput } from "../../deliveryRequest/base/DeliveryRequestWhereUniqueInput";
import { PaymentEventUpdateManyWithoutPaymentsInput } from "./PaymentEventUpdateManyWithoutPaymentsInput";
import { EnumPaymentPaymentType } from "./EnumPaymentPaymentType";
import { EnumPaymentProvider } from "./EnumPaymentProvider";
import { EnumPaymentStatus } from "./EnumPaymentStatus";

@InputType()
class PaymentUpdateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  amount?: number;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  authorizedAt?: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  capturedAt?: Date | null;

  @ApiProperty({
    required: false,
    type: () => DeliveryRequestWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DeliveryRequestWhereUniqueInput)
  @IsOptional()
  @Field(() => DeliveryRequestWhereUniqueInput, {
    nullable: true,
  })
  delivery?: DeliveryRequestWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => PaymentEventUpdateManyWithoutPaymentsInput,
  })
  @ValidateNested()
  @Type(() => PaymentEventUpdateManyWithoutPaymentsInput)
  @IsOptional()
  @Field(() => PaymentEventUpdateManyWithoutPaymentsInput, {
    nullable: true,
  })
  events?: PaymentEventUpdateManyWithoutPaymentsInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  failedAt?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  failureCode?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  failureMessage?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  invoiceId?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  paidAt?: Date | null;

  @ApiProperty({
    required: false,
    enum: EnumPaymentPaymentType,
  })
  @IsEnum(EnumPaymentPaymentType)
  @IsOptional()
  @Field(() => EnumPaymentPaymentType, {
    nullable: true,
  })
  paymentType?: "PREPAID" | "POSTPAID";

  @ApiProperty({
    required: false,
    enum: EnumPaymentProvider,
  })
  @IsEnum(EnumPaymentProvider)
  @IsOptional()
  @Field(() => EnumPaymentProvider, {
    nullable: true,
  })
  provider?: "STRIPE" | "MANUAL" | "OTHER";

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  providerChargeId?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  providerPaymentIntentId?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  refundedAt?: Date | null;

  @ApiProperty({
    required: false,
    enum: EnumPaymentStatus,
  })
  @IsEnum(EnumPaymentStatus)
  @IsOptional()
  @Field(() => EnumPaymentStatus, {
    nullable: true,
  })
  status?:
    | "AUTHORIZED"
    | "CAPTURED"
    | "FAILED"
    | "INVOICED"
    | "PAID"
    | "VOIDED"
    | "REFUNDED";

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  voidedAt?: Date | null;
}

export { PaymentUpdateInput as PaymentUpdateInput };
