/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { DisputeNote } from "./DisputeNote";
import { DisputeNoteCountArgs } from "./DisputeNoteCountArgs";
import { DisputeNoteFindManyArgs } from "./DisputeNoteFindManyArgs";
import { DisputeNoteFindUniqueArgs } from "./DisputeNoteFindUniqueArgs";
import { CreateDisputeNoteArgs } from "./CreateDisputeNoteArgs";
import { UpdateDisputeNoteArgs } from "./UpdateDisputeNoteArgs";
import { DeleteDisputeNoteArgs } from "./DeleteDisputeNoteArgs";
import { User } from "../../user/base/User";
import { DisputeCase } from "../../disputeCase/base/DisputeCase";
import { DisputeNoteService } from "../disputeNote.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => DisputeNote)
export class DisputeNoteResolverBase {
  constructor(
    protected readonly service: DisputeNoteService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "DisputeNote",
    action: "read",
    possession: "any",
  })
  async _disputeNotesMeta(
    @graphql.Args() args: DisputeNoteCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [DisputeNote])
  @nestAccessControl.UseRoles({
    resource: "DisputeNote",
    action: "read",
    possession: "any",
  })
  async disputeNotes(
    @graphql.Args() args: DisputeNoteFindManyArgs
  ): Promise<DisputeNote[]> {
    return this.service.disputeNotes(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => DisputeNote, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "DisputeNote",
    action: "read",
    possession: "own",
  })
  async disputeNote(
    @graphql.Args() args: DisputeNoteFindUniqueArgs
  ): Promise<DisputeNote | null> {
    const result = await this.service.disputeNote(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => DisputeNote)
  @nestAccessControl.UseRoles({
    resource: "DisputeNote",
    action: "create",
    possession: "any",
  })
  async createDisputeNote(
    @graphql.Args() args: CreateDisputeNoteArgs
  ): Promise<DisputeNote> {
    return await this.service.createDisputeNote({
      ...args,
      data: {
        ...args.data,

        author: args.data.author
          ? {
              connect: args.data.author,
            }
          : undefined,

        dispute: {
          connect: args.data.dispute,
        },
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => DisputeNote)
  @nestAccessControl.UseRoles({
    resource: "DisputeNote",
    action: "update",
    possession: "any",
  })
  async updateDisputeNote(
    @graphql.Args() args: UpdateDisputeNoteArgs
  ): Promise<DisputeNote | null> {
    try {
      return await this.service.updateDisputeNote({
        ...args,
        data: {
          ...args.data,

          author: args.data.author
            ? {
                connect: args.data.author,
              }
            : undefined,

          dispute: {
            connect: args.data.dispute,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => DisputeNote)
  @nestAccessControl.UseRoles({
    resource: "DisputeNote",
    action: "delete",
    possession: "any",
  })
  async deleteDisputeNote(
    @graphql.Args() args: DeleteDisputeNoteArgs
  ): Promise<DisputeNote | null> {
    try {
      return await this.service.deleteDisputeNote(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "author",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getAuthor(@graphql.Parent() parent: DisputeNote): Promise<User | null> {
    const result = await this.service.getAuthor(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => DisputeCase, {
    nullable: true,
    name: "dispute",
  })
  @nestAccessControl.UseRoles({
    resource: "DisputeCase",
    action: "read",
    possession: "any",
  })
  async getDispute(
    @graphql.Parent() parent: DisputeNote
  ): Promise<DisputeCase | null> {
    const result = await this.service.getDispute(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
