/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  DisputeNote as PrismaDisputeNote,
  User as PrismaUser,
  DisputeCase as PrismaDisputeCase,
} from "@prisma/client";

export class DisputeNoteServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.DisputeNoteCountArgs, "select">
  ): Promise<number> {
    return this.prisma.disputeNote.count(args);
  }

  async disputeNotes(
    args: Prisma.DisputeNoteFindManyArgs
  ): Promise<PrismaDisputeNote[]> {
    return this.prisma.disputeNote.findMany(args);
  }
  async disputeNote(
    args: Prisma.DisputeNoteFindUniqueArgs
  ): Promise<PrismaDisputeNote | null> {
    return this.prisma.disputeNote.findUnique(args);
  }
  async createDisputeNote(
    args: Prisma.DisputeNoteCreateArgs
  ): Promise<PrismaDisputeNote> {
    return this.prisma.disputeNote.create(args);
  }
  async updateDisputeNote(
    args: Prisma.DisputeNoteUpdateArgs
  ): Promise<PrismaDisputeNote> {
    return this.prisma.disputeNote.update(args);
  }
  async deleteDisputeNote(
    args: Prisma.DisputeNoteDeleteArgs
  ): Promise<PrismaDisputeNote> {
    return this.prisma.disputeNote.delete(args);
  }

  async getAuthor(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.disputeNote
      .findUnique({
        where: { id: parentId },
      })
      .author();
  }

  async getDispute(parentId: string): Promise<PrismaDisputeCase | null> {
    return this.prisma.disputeNote
      .findUnique({
        where: { id: parentId },
      })
      .dispute();
  }
}
