/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Tip as PrismaTip,
  DeliveryRequest as PrismaDeliveryRequest,
} from "@prisma/client";

export class TipServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.TipCountArgs, "select">): Promise<number> {
    return this.prisma.tip.count(args);
  }

  async tips(args: Prisma.TipFindManyArgs): Promise<PrismaTip[]> {
    return this.prisma.tip.findMany(args);
  }
  async tip(args: Prisma.TipFindUniqueArgs): Promise<PrismaTip | null> {
    return this.prisma.tip.findUnique(args);
  }
  async createTip(args: Prisma.TipCreateArgs): Promise<PrismaTip> {
    return this.prisma.tip.create(args);
  }
  async updateTip(args: Prisma.TipUpdateArgs): Promise<PrismaTip> {
    return this.prisma.tip.update(args);
  }
  async deleteTip(args: Prisma.TipDeleteArgs): Promise<PrismaTip> {
    return this.prisma.tip.delete(args);
  }

  async getDelivery(parentId: string): Promise<PrismaDeliveryRequest | null> {
    return this.prisma.tip
      .findUnique({
        where: { id: parentId },
      })
      .delivery();
  }
}
