/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsNumber,
  Max,
  IsDate,
  ValidateNested,
  IsString,
  IsEnum,
  MaxLength,
  IsOptional,
} from "class-validator";

import { Type } from "class-transformer";
import { DeliveryRequest } from "../../deliveryRequest/base/DeliveryRequest";
import { EnumTipProvider } from "./EnumTipProvider";
import { EnumTipStatus } from "./EnumTipStatus";

@ObjectType()
class Tip {
  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @Field(() => Number)
  amount!: number;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
    type: () => DeliveryRequest,
  })
  @ValidateNested()
  @Type(() => DeliveryRequest)
  delivery?: DeliveryRequest;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: true,
    enum: EnumTipProvider,
  })
  @IsEnum(EnumTipProvider)
  @Field(() => EnumTipProvider, {
    nullable: true,
  })
  provider?: "STRIPE" | "MANUAL" | "OTHER";

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  providerRef!: string | null;

  @ApiProperty({
    required: true,
    enum: EnumTipStatus,
  })
  @IsEnum(EnumTipStatus)
  @Field(() => EnumTipStatus, {
    nullable: true,
  })
  status?: "AUTHORIZED" | "CAPTURED" | "FAILED" | "REFUNDED";

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { Tip as Tip };
