/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { TimeSlotTemplate } from "./TimeSlotTemplate";
import { TimeSlotTemplateCountArgs } from "./TimeSlotTemplateCountArgs";
import { TimeSlotTemplateFindManyArgs } from "./TimeSlotTemplateFindManyArgs";
import { TimeSlotTemplateFindUniqueArgs } from "./TimeSlotTemplateFindUniqueArgs";
import { CreateTimeSlotTemplateArgs } from "./CreateTimeSlotTemplateArgs";
import { UpdateTimeSlotTemplateArgs } from "./UpdateTimeSlotTemplateArgs";
import { DeleteTimeSlotTemplateArgs } from "./DeleteTimeSlotTemplateArgs";
import { TimeSlotTemplateService } from "../timeSlotTemplate.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => TimeSlotTemplate)
export class TimeSlotTemplateResolverBase {
  constructor(
    protected readonly service: TimeSlotTemplateService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "TimeSlotTemplate",
    action: "read",
    possession: "any",
  })
  async _timeSlotTemplatesMeta(
    @graphql.Args() args: TimeSlotTemplateCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [TimeSlotTemplate])
  @nestAccessControl.UseRoles({
    resource: "TimeSlotTemplate",
    action: "read",
    possession: "any",
  })
  async timeSlotTemplates(
    @graphql.Args() args: TimeSlotTemplateFindManyArgs
  ): Promise<TimeSlotTemplate[]> {
    return this.service.timeSlotTemplates(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => TimeSlotTemplate, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "TimeSlotTemplate",
    action: "read",
    possession: "own",
  })
  async timeSlotTemplate(
    @graphql.Args() args: TimeSlotTemplateFindUniqueArgs
  ): Promise<TimeSlotTemplate | null> {
    const result = await this.service.timeSlotTemplate(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => TimeSlotTemplate)
  @nestAccessControl.UseRoles({
    resource: "TimeSlotTemplate",
    action: "create",
    possession: "any",
  })
  async createTimeSlotTemplate(
    @graphql.Args() args: CreateTimeSlotTemplateArgs
  ): Promise<TimeSlotTemplate> {
    return await this.service.createTimeSlotTemplate({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => TimeSlotTemplate)
  @nestAccessControl.UseRoles({
    resource: "TimeSlotTemplate",
    action: "update",
    possession: "any",
  })
  async updateTimeSlotTemplate(
    @graphql.Args() args: UpdateTimeSlotTemplateArgs
  ): Promise<TimeSlotTemplate | null> {
    try {
      return await this.service.updateTimeSlotTemplate({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => TimeSlotTemplate)
  @nestAccessControl.UseRoles({
    resource: "TimeSlotTemplate",
    action: "delete",
    possession: "any",
  })
  async deleteTimeSlotTemplate(
    @graphql.Args() args: DeleteTimeSlotTemplateArgs
  ): Promise<TimeSlotTemplate | null> {
    try {
      return await this.service.deleteTimeSlotTemplate(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
