/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, InvestorLead as PrismaInvestorLead } from "@prisma/client";

export class InvestorLeadServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.InvestorLeadCountArgs, "select">
  ): Promise<number> {
    return this.prisma.investorLead.count(args);
  }

  async investorLeads(
    args: Prisma.InvestorLeadFindManyArgs
  ): Promise<PrismaInvestorLead[]> {
    return this.prisma.investorLead.findMany(args);
  }
  async investorLead(
    args: Prisma.InvestorLeadFindUniqueArgs
  ): Promise<PrismaInvestorLead | null> {
    return this.prisma.investorLead.findUnique(args);
  }
  async createInvestorLead(
    args: Prisma.InvestorLeadCreateArgs
  ): Promise<PrismaInvestorLead> {
    return this.prisma.investorLead.create(args);
  }
  async updateInvestorLead(
    args: Prisma.InvestorLeadUpdateArgs
  ): Promise<PrismaInvestorLead> {
    return this.prisma.investorLead.update(args);
  }
  async deleteInvestorLead(
    args: Prisma.InvestorLeadDeleteArgs
  ): Promise<PrismaInvestorLead> {
    return this.prisma.investorLead.delete(args);
  }
}
