/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { DriverLocation } from "./DriverLocation";
import { DriverLocationCountArgs } from "./DriverLocationCountArgs";
import { DriverLocationFindManyArgs } from "./DriverLocationFindManyArgs";
import { DriverLocationFindUniqueArgs } from "./DriverLocationFindUniqueArgs";
import { CreateDriverLocationArgs } from "./CreateDriverLocationArgs";
import { UpdateDriverLocationArgs } from "./UpdateDriverLocationArgs";
import { DeleteDriverLocationArgs } from "./DeleteDriverLocationArgs";
import { Driver } from "../../driver/base/Driver";
import { DriverLocationService } from "../driverLocation.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => DriverLocation)
export class DriverLocationResolverBase {
  constructor(
    protected readonly service: DriverLocationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "DriverLocation",
    action: "read",
    possession: "any",
  })
  async _driverLocationsMeta(
    @graphql.Args() args: DriverLocationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [DriverLocation])
  @nestAccessControl.UseRoles({
    resource: "DriverLocation",
    action: "read",
    possession: "any",
  })
  async driverLocations(
    @graphql.Args() args: DriverLocationFindManyArgs
  ): Promise<DriverLocation[]> {
    return this.service.driverLocations(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => DriverLocation, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "DriverLocation",
    action: "read",
    possession: "own",
  })
  async driverLocation(
    @graphql.Args() args: DriverLocationFindUniqueArgs
  ): Promise<DriverLocation | null> {
    const result = await this.service.driverLocation(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => DriverLocation)
  @nestAccessControl.UseRoles({
    resource: "DriverLocation",
    action: "create",
    possession: "any",
  })
  async createDriverLocation(
    @graphql.Args() args: CreateDriverLocationArgs
  ): Promise<DriverLocation> {
    return await this.service.createDriverLocation({
      ...args,
      data: {
        ...args.data,

        driver: {
          connect: args.data.driver,
        },
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => DriverLocation)
  @nestAccessControl.UseRoles({
    resource: "DriverLocation",
    action: "update",
    possession: "any",
  })
  async updateDriverLocation(
    @graphql.Args() args: UpdateDriverLocationArgs
  ): Promise<DriverLocation | null> {
    try {
      return await this.service.updateDriverLocation({
        ...args,
        data: {
          ...args.data,

          driver: {
            connect: args.data.driver,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => DriverLocation)
  @nestAccessControl.UseRoles({
    resource: "DriverLocation",
    action: "delete",
    possession: "any",
  })
  async deleteDriverLocation(
    @graphql.Args() args: DeleteDriverLocationArgs
  ): Promise<DriverLocation | null> {
    try {
      return await this.service.deleteDriverLocation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Driver, {
    nullable: true,
    name: "driver",
  })
  @nestAccessControl.UseRoles({
    resource: "Driver",
    action: "read",
    possession: "any",
  })
  async getDriver(
    @graphql.Parent() parent: DriverLocation
  ): Promise<Driver | null> {
    const result = await this.service.getDriver(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
