/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  DriverLocation as PrismaDriverLocation,
  Driver as PrismaDriver,
} from "@prisma/client";

export class DriverLocationServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.DriverLocationCountArgs, "select">
  ): Promise<number> {
    return this.prisma.driverLocation.count(args);
  }

  async driverLocations(
    args: Prisma.DriverLocationFindManyArgs
  ): Promise<PrismaDriverLocation[]> {
    return this.prisma.driverLocation.findMany(args);
  }
  async driverLocation(
    args: Prisma.DriverLocationFindUniqueArgs
  ): Promise<PrismaDriverLocation | null> {
    return this.prisma.driverLocation.findUnique(args);
  }
  async createDriverLocation(
    args: Prisma.DriverLocationCreateArgs
  ): Promise<PrismaDriverLocation> {
    return this.prisma.driverLocation.create(args);
  }
  async updateDriverLocation(
    args: Prisma.DriverLocationUpdateArgs
  ): Promise<PrismaDriverLocation> {
    return this.prisma.driverLocation.update(args);
  }
  async deleteDriverLocation(
    args: Prisma.DriverLocationDeleteArgs
  ): Promise<PrismaDriverLocation> {
    return this.prisma.driverLocation.delete(args);
  }

  async getDriver(parentId: string): Promise<PrismaDriver | null> {
    return this.prisma.driverLocation
      .findUnique({
        where: { id: parentId },
      })
      .driver();
  }
}
