/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, OperatingHour as PrismaOperatingHour } from "@prisma/client";

export class OperatingHourServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.OperatingHourCountArgs, "select">
  ): Promise<number> {
    return this.prisma.operatingHour.count(args);
  }

  async operatingHours(
    args: Prisma.OperatingHourFindManyArgs
  ): Promise<PrismaOperatingHour[]> {
    return this.prisma.operatingHour.findMany(args);
  }
  async operatingHour(
    args: Prisma.OperatingHourFindUniqueArgs
  ): Promise<PrismaOperatingHour | null> {
    return this.prisma.operatingHour.findUnique(args);
  }
  async createOperatingHour(
    args: Prisma.OperatingHourCreateArgs
  ): Promise<PrismaOperatingHour> {
    return this.prisma.operatingHour.create(args);
  }
  async updateOperatingHour(
    args: Prisma.OperatingHourUpdateArgs
  ): Promise<PrismaOperatingHour> {
    return this.prisma.operatingHour.update(args);
  }
  async deleteOperatingHour(
    args: Prisma.OperatingHourDeleteArgs
  ): Promise<PrismaOperatingHour> {
    return this.prisma.operatingHour.delete(args);
  }
}
