/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { OperatingHour } from "./OperatingHour";
import { OperatingHourCountArgs } from "./OperatingHourCountArgs";
import { OperatingHourFindManyArgs } from "./OperatingHourFindManyArgs";
import { OperatingHourFindUniqueArgs } from "./OperatingHourFindUniqueArgs";
import { CreateOperatingHourArgs } from "./CreateOperatingHourArgs";
import { UpdateOperatingHourArgs } from "./UpdateOperatingHourArgs";
import { DeleteOperatingHourArgs } from "./DeleteOperatingHourArgs";
import { OperatingHourService } from "../operatingHour.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => OperatingHour)
export class OperatingHourResolverBase {
  constructor(
    protected readonly service: OperatingHourService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "OperatingHour",
    action: "read",
    possession: "any",
  })
  async _operatingHoursMeta(
    @graphql.Args() args: OperatingHourCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [OperatingHour])
  @nestAccessControl.UseRoles({
    resource: "OperatingHour",
    action: "read",
    possession: "any",
  })
  async operatingHours(
    @graphql.Args() args: OperatingHourFindManyArgs
  ): Promise<OperatingHour[]> {
    return this.service.operatingHours(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => OperatingHour, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "OperatingHour",
    action: "read",
    possession: "own",
  })
  async operatingHour(
    @graphql.Args() args: OperatingHourFindUniqueArgs
  ): Promise<OperatingHour | null> {
    const result = await this.service.operatingHour(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => OperatingHour)
  @nestAccessControl.UseRoles({
    resource: "OperatingHour",
    action: "create",
    possession: "any",
  })
  async createOperatingHour(
    @graphql.Args() args: CreateOperatingHourArgs
  ): Promise<OperatingHour> {
    return await this.service.createOperatingHour({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => OperatingHour)
  @nestAccessControl.UseRoles({
    resource: "OperatingHour",
    action: "update",
    possession: "any",
  })
  async updateOperatingHour(
    @graphql.Args() args: UpdateOperatingHourArgs
  ): Promise<OperatingHour | null> {
    try {
      return await this.service.updateOperatingHour({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => OperatingHour)
  @nestAccessControl.UseRoles({
    resource: "OperatingHour",
    action: "delete",
    possession: "any",
  })
  async deleteOperatingHour(
    @graphql.Args() args: DeleteOperatingHourArgs
  ): Promise<OperatingHour | null> {
    try {
      return await this.service.deleteOperatingHour(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
