/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SavedVehicleService } from "../savedVehicle.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SavedVehicleCreateInput } from "./SavedVehicleCreateInput";
import { SavedVehicle } from "./SavedVehicle";
import { SavedVehicleFindManyArgs } from "./SavedVehicleFindManyArgs";
import { SavedVehicleWhereUniqueInput } from "./SavedVehicleWhereUniqueInput";
import { SavedVehicleUpdateInput } from "./SavedVehicleUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SavedVehicleControllerBase {
  constructor(
    protected readonly service: SavedVehicleService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SavedVehicle })
  @nestAccessControl.UseRoles({
    resource: "SavedVehicle",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSavedVehicle(
    @common.Body() data: SavedVehicleCreateInput
  ): Promise<SavedVehicle> {
    return await this.service.createSavedVehicle({
      data: {
        ...data,

        customer: {
          connect: data.customer,
        },
      },
      select: {
        color: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        id: true,
        licensePlate: true,
        make: true,
        model: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [SavedVehicle] })
  @ApiNestedQuery(SavedVehicleFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SavedVehicle",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async savedVehicles(@common.Req() request: Request): Promise<SavedVehicle[]> {
    const args = plainToClass(SavedVehicleFindManyArgs, request.query);
    return this.service.savedVehicles({
      ...args,
      select: {
        color: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        id: true,
        licensePlate: true,
        make: true,
        model: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SavedVehicle })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SavedVehicle",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async savedVehicle(
    @common.Param() params: SavedVehicleWhereUniqueInput
  ): Promise<SavedVehicle | null> {
    const result = await this.service.savedVehicle({
      where: params,
      select: {
        color: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        id: true,
        licensePlate: true,
        make: true,
        model: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SavedVehicle })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SavedVehicle",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSavedVehicle(
    @common.Param() params: SavedVehicleWhereUniqueInput,
    @common.Body() data: SavedVehicleUpdateInput
  ): Promise<SavedVehicle | null> {
    try {
      return await this.service.updateSavedVehicle({
        where: params,
        data: {
          ...data,

          customer: {
            connect: data.customer,
          },
        },
        select: {
          color: true,
          createdAt: true,

          customer: {
            select: {
              id: true,
            },
          },

          id: true,
          licensePlate: true,
          make: true,
          model: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SavedVehicle })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SavedVehicle",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSavedVehicle(
    @common.Param() params: SavedVehicleWhereUniqueInput
  ): Promise<SavedVehicle | null> {
    try {
      return await this.service.deleteSavedVehicle({
        where: params,
        select: {
          color: true,
          createdAt: true,

          customer: {
            select: {
              id: true,
            },
          },

          id: true,
          licensePlate: true,
          make: true,
          model: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
