/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  SavedVehicle as PrismaSavedVehicle,
  Customer as PrismaCustomer,
} from "@prisma/client";

export class SavedVehicleServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.SavedVehicleCountArgs, "select">
  ): Promise<number> {
    return this.prisma.savedVehicle.count(args);
  }

  async savedVehicles(
    args: Prisma.SavedVehicleFindManyArgs
  ): Promise<PrismaSavedVehicle[]> {
    return this.prisma.savedVehicle.findMany(args);
  }
  async savedVehicle(
    args: Prisma.SavedVehicleFindUniqueArgs
  ): Promise<PrismaSavedVehicle | null> {
    return this.prisma.savedVehicle.findUnique(args);
  }
  async createSavedVehicle(
    args: Prisma.SavedVehicleCreateArgs
  ): Promise<PrismaSavedVehicle> {
    return this.prisma.savedVehicle.create(args);
  }
  async updateSavedVehicle(
    args: Prisma.SavedVehicleUpdateArgs
  ): Promise<PrismaSavedVehicle> {
    return this.prisma.savedVehicle.update(args);
  }
  async deleteSavedVehicle(
    args: Prisma.SavedVehicleDeleteArgs
  ): Promise<PrismaSavedVehicle> {
    return this.prisma.savedVehicle.delete(args);
  }

  async getCustomer(parentId: string): Promise<PrismaCustomer | null> {
    return this.prisma.savedVehicle
      .findUnique({
        where: { id: parentId },
      })
      .customer();
  }
}
