/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumAdminAuditLogAction } from "./EnumAdminAuditLogAction";
import {
  IsEnum,
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { Type } from "class-transformer";
import { EnumAdminAuditLogActorType } from "./EnumAdminAuditLogActorType";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { CustomerWhereUniqueInput } from "../../customer/base/CustomerWhereUniqueInput";
import { DeliveryRequestWhereUniqueInput } from "../../deliveryRequest/base/DeliveryRequestWhereUniqueInput";
import { DriverWhereUniqueInput } from "../../driver/base/DriverWhereUniqueInput";

@InputType()
class AdminAuditLogCreateInput {
  @ApiProperty({
    required: true,
    enum: EnumAdminAuditLogAction,
  })
  @IsEnum(EnumAdminAuditLogAction)
  @Field(() => EnumAdminAuditLogAction)
  action!:
    | "USER_DISABLE"
    | "USER_ENABLE"
    | "DEALER_APPROVE"
    | "DEALER_REJECT"
    | "DRIVER_APPROVE"
    | "DRIVER_SUSPEND"
    | "DRIVER_UNSUSPEND"
    | "DELIVERY_CANCEL"
    | "DELIVERY_REASSIGN"
    | "PRICING_UPDATE"
    | "POLICY_UPDATE"
    | "DISPUTE_UPDATE"
    | "PAYMENT_OVERRIDE"
    | "PAYOUT_OVERRIDE"
    | "OTHER";

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  actor?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: true,
    enum: EnumAdminAuditLogActorType,
  })
  @IsEnum(EnumAdminAuditLogActorType)
  @Field(() => EnumAdminAuditLogActorType)
  actorType!: "USER" | "SYSTEM";

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  afterJson?: InputJsonValue;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  beforeJson?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => CustomerWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CustomerWhereUniqueInput)
  @IsOptional()
  @Field(() => CustomerWhereUniqueInput, {
    nullable: true,
  })
  customer?: CustomerWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => DeliveryRequestWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DeliveryRequestWhereUniqueInput)
  @IsOptional()
  @Field(() => DeliveryRequestWhereUniqueInput, {
    nullable: true,
  })
  delivery?: DeliveryRequestWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => DriverWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DriverWhereUniqueInput)
  @IsOptional()
  @Field(() => DriverWhereUniqueInput, {
    nullable: true,
  })
  driver?: DriverWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  reason?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { AdminAuditLogCreateInput as AdminAuditLogCreateInput };
