/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  AdminAuditLog as PrismaAdminAuditLog,
  User as PrismaUser,
  Customer as PrismaCustomer,
  DeliveryRequest as PrismaDeliveryRequest,
  Driver as PrismaDriver,
} from "@prisma/client";

export class AdminAuditLogServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.AdminAuditLogCountArgs, "select">
  ): Promise<number> {
    return this.prisma.adminAuditLog.count(args);
  }

  async adminAuditLogs(
    args: Prisma.AdminAuditLogFindManyArgs
  ): Promise<PrismaAdminAuditLog[]> {
    return this.prisma.adminAuditLog.findMany(args);
  }
  async adminAuditLog(
    args: Prisma.AdminAuditLogFindUniqueArgs
  ): Promise<PrismaAdminAuditLog | null> {
    return this.prisma.adminAuditLog.findUnique(args);
  }
  async createAdminAuditLog(
    args: Prisma.AdminAuditLogCreateArgs
  ): Promise<PrismaAdminAuditLog> {
    return this.prisma.adminAuditLog.create(args);
  }
  async updateAdminAuditLog(
    args: Prisma.AdminAuditLogUpdateArgs
  ): Promise<PrismaAdminAuditLog> {
    return this.prisma.adminAuditLog.update(args);
  }
  async deleteAdminAuditLog(
    args: Prisma.AdminAuditLogDeleteArgs
  ): Promise<PrismaAdminAuditLog> {
    return this.prisma.adminAuditLog.delete(args);
  }

  async getActor(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.adminAuditLog
      .findUnique({
        where: { id: parentId },
      })
      .actor();
  }

  async getCustomer(parentId: string): Promise<PrismaCustomer | null> {
    return this.prisma.adminAuditLog
      .findUnique({
        where: { id: parentId },
      })
      .customer();
  }

  async getDelivery(parentId: string): Promise<PrismaDeliveryRequest | null> {
    return this.prisma.adminAuditLog
      .findUnique({
        where: { id: parentId },
      })
      .delivery();
  }

  async getDriver(parentId: string): Promise<PrismaDriver | null> {
    return this.prisma.adminAuditLog
      .findUnique({
        where: { id: parentId },
      })
      .driver();
  }

  async getUser(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.adminAuditLog
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
