/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AdminAuditLog } from "./AdminAuditLog";
import { AdminAuditLogCountArgs } from "./AdminAuditLogCountArgs";
import { AdminAuditLogFindManyArgs } from "./AdminAuditLogFindManyArgs";
import { AdminAuditLogFindUniqueArgs } from "./AdminAuditLogFindUniqueArgs";
import { CreateAdminAuditLogArgs } from "./CreateAdminAuditLogArgs";
import { UpdateAdminAuditLogArgs } from "./UpdateAdminAuditLogArgs";
import { DeleteAdminAuditLogArgs } from "./DeleteAdminAuditLogArgs";
import { User } from "../../user/base/User";
import { Customer } from "../../customer/base/Customer";
import { DeliveryRequest } from "../../deliveryRequest/base/DeliveryRequest";
import { Driver } from "../../driver/base/Driver";
import { AdminAuditLogService } from "../adminAuditLog.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => AdminAuditLog)
export class AdminAuditLogResolverBase {
  constructor(
    protected readonly service: AdminAuditLogService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "AdminAuditLog",
    action: "read",
    possession: "any",
  })
  async _adminAuditLogsMeta(
    @graphql.Args() args: AdminAuditLogCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [AdminAuditLog])
  @nestAccessControl.UseRoles({
    resource: "AdminAuditLog",
    action: "read",
    possession: "any",
  })
  async adminAuditLogs(
    @graphql.Args() args: AdminAuditLogFindManyArgs
  ): Promise<AdminAuditLog[]> {
    return this.service.adminAuditLogs(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => AdminAuditLog, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "AdminAuditLog",
    action: "read",
    possession: "own",
  })
  async adminAuditLog(
    @graphql.Args() args: AdminAuditLogFindUniqueArgs
  ): Promise<AdminAuditLog | null> {
    const result = await this.service.adminAuditLog(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => AdminAuditLog)
  @nestAccessControl.UseRoles({
    resource: "AdminAuditLog",
    action: "create",
    possession: "any",
  })
  async createAdminAuditLog(
    @graphql.Args() args: CreateAdminAuditLogArgs
  ): Promise<AdminAuditLog> {
    return await this.service.createAdminAuditLog({
      ...args,
      data: {
        ...args.data,

        actor: args.data.actor
          ? {
              connect: args.data.actor,
            }
          : undefined,

        customer: args.data.customer
          ? {
              connect: args.data.customer,
            }
          : undefined,

        delivery: args.data.delivery
          ? {
              connect: args.data.delivery,
            }
          : undefined,

        driver: args.data.driver
          ? {
              connect: args.data.driver,
            }
          : undefined,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => AdminAuditLog)
  @nestAccessControl.UseRoles({
    resource: "AdminAuditLog",
    action: "update",
    possession: "any",
  })
  async updateAdminAuditLog(
    @graphql.Args() args: UpdateAdminAuditLogArgs
  ): Promise<AdminAuditLog | null> {
    try {
      return await this.service.updateAdminAuditLog({
        ...args,
        data: {
          ...args.data,

          actor: args.data.actor
            ? {
                connect: args.data.actor,
              }
            : undefined,

          customer: args.data.customer
            ? {
                connect: args.data.customer,
              }
            : undefined,

          delivery: args.data.delivery
            ? {
                connect: args.data.delivery,
              }
            : undefined,

          driver: args.data.driver
            ? {
                connect: args.data.driver,
              }
            : undefined,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => AdminAuditLog)
  @nestAccessControl.UseRoles({
    resource: "AdminAuditLog",
    action: "delete",
    possession: "any",
  })
  async deleteAdminAuditLog(
    @graphql.Args() args: DeleteAdminAuditLogArgs
  ): Promise<AdminAuditLog | null> {
    try {
      return await this.service.deleteAdminAuditLog(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "actor",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getActor(
    @graphql.Parent() parent: AdminAuditLog
  ): Promise<User | null> {
    const result = await this.service.getActor(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Customer, {
    nullable: true,
    name: "customer",
  })
  @nestAccessControl.UseRoles({
    resource: "Customer",
    action: "read",
    possession: "any",
  })
  async getCustomer(
    @graphql.Parent() parent: AdminAuditLog
  ): Promise<Customer | null> {
    const result = await this.service.getCustomer(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => DeliveryRequest, {
    nullable: true,
    name: "delivery",
  })
  @nestAccessControl.UseRoles({
    resource: "DeliveryRequest",
    action: "read",
    possession: "any",
  })
  async getDelivery(
    @graphql.Parent() parent: AdminAuditLog
  ): Promise<DeliveryRequest | null> {
    const result = await this.service.getDelivery(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Driver, {
    nullable: true,
    name: "driver",
  })
  @nestAccessControl.UseRoles({
    resource: "Driver",
    action: "read",
    possession: "any",
  })
  async getDriver(
    @graphql.Parent() parent: AdminAuditLog
  ): Promise<Driver | null> {
    const result = await this.service.getDriver(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: AdminAuditLog): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
