/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumAdminAuditLogAction } from "./EnumAdminAuditLogAction";
import {
  IsEnum,
  ValidateNested,
  IsOptional,
  IsDate,
  IsString,
  MaxLength,
} from "class-validator";
import { User } from "../../user/base/User";
import { Type } from "class-transformer";
import { EnumAdminAuditLogActorType } from "./EnumAdminAuditLogActorType";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { JsonValue } from "type-fest";
import { Customer } from "../../customer/base/Customer";
import { DeliveryRequest } from "../../deliveryRequest/base/DeliveryRequest";
import { Driver } from "../../driver/base/Driver";

@ObjectType()
class AdminAuditLog {
  @ApiProperty({
    required: true,
    enum: EnumAdminAuditLogAction,
  })
  @IsEnum(EnumAdminAuditLogAction)
  @Field(() => EnumAdminAuditLogAction, {
    nullable: true,
  })
  action?:
    | "USER_DISABLE"
    | "USER_ENABLE"
    | "DEALER_APPROVE"
    | "DEALER_REJECT"
    | "DRIVER_APPROVE"
    | "DRIVER_SUSPEND"
    | "DRIVER_UNSUSPEND"
    | "DELIVERY_CANCEL"
    | "DELIVERY_REASSIGN"
    | "PRICING_UPDATE"
    | "POLICY_UPDATE"
    | "DISPUTE_UPDATE"
    | "PAYMENT_OVERRIDE"
    | "PAYOUT_OVERRIDE"
    | "OTHER";

  @ApiProperty({
    required: false,
    type: () => User,
  })
  @ValidateNested()
  @Type(() => User)
  @IsOptional()
  actor?: User | null;

  @ApiProperty({
    required: true,
    enum: EnumAdminAuditLogActorType,
  })
  @IsEnum(EnumAdminAuditLogActorType)
  @Field(() => EnumAdminAuditLogActorType, {
    nullable: true,
  })
  actorType?: "USER" | "SYSTEM";

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  afterJson!: JsonValue;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  beforeJson!: JsonValue;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: () => Customer,
  })
  @ValidateNested()
  @Type(() => Customer)
  @IsOptional()
  customer?: Customer | null;

  @ApiProperty({
    required: false,
    type: () => DeliveryRequest,
  })
  @ValidateNested()
  @Type(() => DeliveryRequest)
  @IsOptional()
  delivery?: DeliveryRequest | null;

  @ApiProperty({
    required: false,
    type: () => Driver,
  })
  @ValidateNested()
  @Type(() => Driver)
  @IsOptional()
  driver?: Driver | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  reason!: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    type: () => User,
  })
  @ValidateNested()
  @Type(() => User)
  @IsOptional()
  user?: User | null;
}

export { AdminAuditLog as AdminAuditLog };
