/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { PricingConfig } from "./PricingConfig";
import { PricingConfigCountArgs } from "./PricingConfigCountArgs";
import { PricingConfigFindManyArgs } from "./PricingConfigFindManyArgs";
import { PricingConfigFindUniqueArgs } from "./PricingConfigFindUniqueArgs";
import { CreatePricingConfigArgs } from "./CreatePricingConfigArgs";
import { UpdatePricingConfigArgs } from "./UpdatePricingConfigArgs";
import { DeletePricingConfigArgs } from "./DeletePricingConfigArgs";
import { PricingCategoryRuleFindManyArgs } from "../../pricingCategoryRule/base/PricingCategoryRuleFindManyArgs";
import { PricingCategoryRule } from "../../pricingCategoryRule/base/PricingCategoryRule";
import { CustomerFindManyArgs } from "../../customer/base/CustomerFindManyArgs";
import { Customer } from "../../customer/base/Customer";
import { PricingTierFindManyArgs } from "../../pricingTier/base/PricingTierFindManyArgs";
import { PricingTier } from "../../pricingTier/base/PricingTier";
import { PricingConfigService } from "../pricingConfig.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => PricingConfig)
export class PricingConfigResolverBase {
  constructor(
    protected readonly service: PricingConfigService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "PricingConfig",
    action: "read",
    possession: "any",
  })
  async _pricingConfigsMeta(
    @graphql.Args() args: PricingConfigCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [PricingConfig])
  @nestAccessControl.UseRoles({
    resource: "PricingConfig",
    action: "read",
    possession: "any",
  })
  async pricingConfigs(
    @graphql.Args() args: PricingConfigFindManyArgs
  ): Promise<PricingConfig[]> {
    return this.service.pricingConfigs(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => PricingConfig, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PricingConfig",
    action: "read",
    possession: "own",
  })
  async pricingConfig(
    @graphql.Args() args: PricingConfigFindUniqueArgs
  ): Promise<PricingConfig | null> {
    const result = await this.service.pricingConfig(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => PricingConfig)
  @nestAccessControl.UseRoles({
    resource: "PricingConfig",
    action: "create",
    possession: "any",
  })
  async createPricingConfig(
    @graphql.Args() args: CreatePricingConfigArgs
  ): Promise<PricingConfig> {
    return await this.service.createPricingConfig({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => PricingConfig)
  @nestAccessControl.UseRoles({
    resource: "PricingConfig",
    action: "update",
    possession: "any",
  })
  async updatePricingConfig(
    @graphql.Args() args: UpdatePricingConfigArgs
  ): Promise<PricingConfig | null> {
    try {
      return await this.service.updatePricingConfig({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => PricingConfig)
  @nestAccessControl.UseRoles({
    resource: "PricingConfig",
    action: "delete",
    possession: "any",
  })
  async deletePricingConfig(
    @graphql.Args() args: DeletePricingConfigArgs
  ): Promise<PricingConfig | null> {
    try {
      return await this.service.deletePricingConfig(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [PricingCategoryRule], { name: "categoryRules" })
  @nestAccessControl.UseRoles({
    resource: "PricingCategoryRule",
    action: "read",
    possession: "any",
  })
  async findCategoryRules(
    @graphql.Parent() parent: PricingConfig,
    @graphql.Args() args: PricingCategoryRuleFindManyArgs
  ): Promise<PricingCategoryRule[]> {
    const results = await this.service.findCategoryRules(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Customer], { name: "customers" })
  @nestAccessControl.UseRoles({
    resource: "Customer",
    action: "read",
    possession: "any",
  })
  async findCustomers(
    @graphql.Parent() parent: PricingConfig,
    @graphql.Args() args: CustomerFindManyArgs
  ): Promise<Customer[]> {
    const results = await this.service.findCustomers(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [PricingTier], { name: "tiers" })
  @nestAccessControl.UseRoles({
    resource: "PricingTier",
    action: "read",
    possession: "any",
  })
  async findTiers(
    @graphql.Parent() parent: PricingConfig,
    @graphql.Args() args: PricingTierFindManyArgs
  ): Promise<PricingTier[]> {
    const results = await this.service.findTiers(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
