/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsBoolean,
  IsOptional,
  IsNumber,
  Max,
  ValidateNested,
  IsString,
  MaxLength,
  IsEnum,
} from "class-validator";

import { PricingCategoryRuleUpdateManyWithoutPricingConfigsInput } from "./PricingCategoryRuleUpdateManyWithoutPricingConfigsInput";
import { Type } from "class-transformer";
import { CustomerUpdateManyWithoutPricingConfigsInput } from "./CustomerUpdateManyWithoutPricingConfigsInput";
import { EnumPricingConfigPricingMode } from "./EnumPricingConfigPricingMode";
import { PricingTierUpdateManyWithoutPricingConfigsInput } from "./PricingTierUpdateManyWithoutPricingConfigsInput";

@InputType()
class PricingConfigUpdateInput {
  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  active?: boolean;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  baseFee?: number;

  @ApiProperty({
    required: false,
    type: () => PricingCategoryRuleUpdateManyWithoutPricingConfigsInput,
  })
  @ValidateNested()
  @Type(() => PricingCategoryRuleUpdateManyWithoutPricingConfigsInput)
  @IsOptional()
  @Field(() => PricingCategoryRuleUpdateManyWithoutPricingConfigsInput, {
    nullable: true,
  })
  categoryRules?: PricingCategoryRuleUpdateManyWithoutPricingConfigsInput;

  @ApiProperty({
    required: false,
    type: () => CustomerUpdateManyWithoutPricingConfigsInput,
  })
  @ValidateNested()
  @Type(() => CustomerUpdateManyWithoutPricingConfigsInput)
  @IsOptional()
  @Field(() => CustomerUpdateManyWithoutPricingConfigsInput, {
    nullable: true,
  })
  customers?: CustomerUpdateManyWithoutPricingConfigsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  driverSharePct?: number;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  feePassThrough?: boolean;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  insuranceFee?: number;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  perMileRate?: number | null;

  @ApiProperty({
    required: false,
    enum: EnumPricingConfigPricingMode,
  })
  @IsEnum(EnumPricingConfigPricingMode)
  @IsOptional()
  @Field(() => EnumPricingConfigPricingMode, {
    nullable: true,
  })
  pricingMode?: "PER_MILE" | "FLAT_TIER" | "CATEGORY_ABC";

  @ApiProperty({
    required: false,
    type: () => PricingTierUpdateManyWithoutPricingConfigsInput,
  })
  @ValidateNested()
  @Type(() => PricingTierUpdateManyWithoutPricingConfigsInput)
  @IsOptional()
  @Field(() => PricingTierUpdateManyWithoutPricingConfigsInput, {
    nullable: true,
  })
  tiers?: PricingTierUpdateManyWithoutPricingConfigsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  transactionFeeFixed?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  transactionFeePct?: number | null;
}

export { PricingConfigUpdateInput as PricingConfigUpdateInput };
