/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PricingConfigService } from "../pricingConfig.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PricingConfigCreateInput } from "./PricingConfigCreateInput";
import { PricingConfig } from "./PricingConfig";
import { PricingConfigFindManyArgs } from "./PricingConfigFindManyArgs";
import { PricingConfigWhereUniqueInput } from "./PricingConfigWhereUniqueInput";
import { PricingConfigUpdateInput } from "./PricingConfigUpdateInput";
import { PricingCategoryRuleFindManyArgs } from "../../pricingCategoryRule/base/PricingCategoryRuleFindManyArgs";
import { PricingCategoryRule } from "../../pricingCategoryRule/base/PricingCategoryRule";
import { PricingCategoryRuleWhereUniqueInput } from "../../pricingCategoryRule/base/PricingCategoryRuleWhereUniqueInput";
import { CustomerFindManyArgs } from "../../customer/base/CustomerFindManyArgs";
import { Customer } from "../../customer/base/Customer";
import { CustomerWhereUniqueInput } from "../../customer/base/CustomerWhereUniqueInput";
import { PricingTierFindManyArgs } from "../../pricingTier/base/PricingTierFindManyArgs";
import { PricingTier } from "../../pricingTier/base/PricingTier";
import { PricingTierWhereUniqueInput } from "../../pricingTier/base/PricingTierWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PricingConfigControllerBase {
  constructor(
    protected readonly service: PricingConfigService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PricingConfig })
  @nestAccessControl.UseRoles({
    resource: "PricingConfig",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPricingConfig(
    @common.Body() data: PricingConfigCreateInput
  ): Promise<PricingConfig> {
    return await this.service.createPricingConfig({
      data: data,
      select: {
        active: true,
        baseFee: true,
        createdAt: true,
        description: true,
        driverSharePct: true,
        feePassThrough: true,
        id: true,
        insuranceFee: true,
        name: true,
        perMileRate: true,
        pricingMode: true,
        transactionFeeFixed: true,
        transactionFeePct: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PricingConfig] })
  @ApiNestedQuery(PricingConfigFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PricingConfig",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async pricingConfigs(
    @common.Req() request: Request
  ): Promise<PricingConfig[]> {
    const args = plainToClass(PricingConfigFindManyArgs, request.query);
    return this.service.pricingConfigs({
      ...args,
      select: {
        active: true,
        baseFee: true,
        createdAt: true,
        description: true,
        driverSharePct: true,
        feePassThrough: true,
        id: true,
        insuranceFee: true,
        name: true,
        perMileRate: true,
        pricingMode: true,
        transactionFeeFixed: true,
        transactionFeePct: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PricingConfig })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PricingConfig",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async pricingConfig(
    @common.Param() params: PricingConfigWhereUniqueInput
  ): Promise<PricingConfig | null> {
    const result = await this.service.pricingConfig({
      where: params,
      select: {
        active: true,
        baseFee: true,
        createdAt: true,
        description: true,
        driverSharePct: true,
        feePassThrough: true,
        id: true,
        insuranceFee: true,
        name: true,
        perMileRate: true,
        pricingMode: true,
        transactionFeeFixed: true,
        transactionFeePct: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PricingConfig })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PricingConfig",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePricingConfig(
    @common.Param() params: PricingConfigWhereUniqueInput,
    @common.Body() data: PricingConfigUpdateInput
  ): Promise<PricingConfig | null> {
    try {
      return await this.service.updatePricingConfig({
        where: params,
        data: data,
        select: {
          active: true,
          baseFee: true,
          createdAt: true,
          description: true,
          driverSharePct: true,
          feePassThrough: true,
          id: true,
          insuranceFee: true,
          name: true,
          perMileRate: true,
          pricingMode: true,
          transactionFeeFixed: true,
          transactionFeePct: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PricingConfig })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PricingConfig",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePricingConfig(
    @common.Param() params: PricingConfigWhereUniqueInput
  ): Promise<PricingConfig | null> {
    try {
      return await this.service.deletePricingConfig({
        where: params,
        select: {
          active: true,
          baseFee: true,
          createdAt: true,
          description: true,
          driverSharePct: true,
          feePassThrough: true,
          id: true,
          insuranceFee: true,
          name: true,
          perMileRate: true,
          pricingMode: true,
          transactionFeeFixed: true,
          transactionFeePct: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/categoryRules")
  @ApiNestedQuery(PricingCategoryRuleFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PricingCategoryRule",
    action: "read",
    possession: "any",
  })
  async findCategoryRules(
    @common.Req() request: Request,
    @common.Param() params: PricingConfigWhereUniqueInput
  ): Promise<PricingCategoryRule[]> {
    const query = plainToClass(PricingCategoryRuleFindManyArgs, request.query);
    const results = await this.service.findCategoryRules(params.id, {
      ...query,
      select: {
        baseFee: true,
        category: true,
        createdAt: true,
        flatPrice: true,
        id: true,
        maxMiles: true,
        minMiles: true,
        perMileRate: true,

        pricingConfig: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/categoryRules")
  @nestAccessControl.UseRoles({
    resource: "PricingConfig",
    action: "update",
    possession: "any",
  })
  async connectCategoryRules(
    @common.Param() params: PricingConfigWhereUniqueInput,
    @common.Body() body: PricingCategoryRuleWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      categoryRules: {
        connect: body,
      },
    };
    await this.service.updatePricingConfig({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/categoryRules")
  @nestAccessControl.UseRoles({
    resource: "PricingConfig",
    action: "update",
    possession: "any",
  })
  async updateCategoryRules(
    @common.Param() params: PricingConfigWhereUniqueInput,
    @common.Body() body: PricingCategoryRuleWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      categoryRules: {
        set: body,
      },
    };
    await this.service.updatePricingConfig({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/categoryRules")
  @nestAccessControl.UseRoles({
    resource: "PricingConfig",
    action: "update",
    possession: "any",
  })
  async disconnectCategoryRules(
    @common.Param() params: PricingConfigWhereUniqueInput,
    @common.Body() body: PricingCategoryRuleWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      categoryRules: {
        disconnect: body,
      },
    };
    await this.service.updatePricingConfig({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/customers")
  @ApiNestedQuery(CustomerFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Customer",
    action: "read",
    possession: "any",
  })
  async findCustomers(
    @common.Req() request: Request,
    @common.Param() params: PricingConfigWhereUniqueInput
  ): Promise<Customer[]> {
    const query = plainToClass(CustomerFindManyArgs, request.query);
    const results = await this.service.findCustomers(params.id, {
      ...query,
      select: {
        approvalStatus: true,
        approvedAt: true,

        approvedBy: {
          select: {
            id: true,
          },
        },

        businessAddress: true,
        businessName: true,
        businessPhone: true,
        businessPlaceId: true,
        businessWebsite: true,
        contactEmail: true,
        contactName: true,
        contactPhone: true,
        createdAt: true,
        customerType: true,

        defaultPickup: {
          select: {
            id: true,
          },
        },

        id: true,
        phone: true,
        postpaidEnabled: true,

        pricingConfig: {
          select: {
            id: true,
          },
        },

        pricingModeOverride: true,
        suspendedAt: true,
        suspensionReason: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/customers")
  @nestAccessControl.UseRoles({
    resource: "PricingConfig",
    action: "update",
    possession: "any",
  })
  async connectCustomers(
    @common.Param() params: PricingConfigWhereUniqueInput,
    @common.Body() body: CustomerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      customers: {
        connect: body,
      },
    };
    await this.service.updatePricingConfig({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/customers")
  @nestAccessControl.UseRoles({
    resource: "PricingConfig",
    action: "update",
    possession: "any",
  })
  async updateCustomers(
    @common.Param() params: PricingConfigWhereUniqueInput,
    @common.Body() body: CustomerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      customers: {
        set: body,
      },
    };
    await this.service.updatePricingConfig({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/customers")
  @nestAccessControl.UseRoles({
    resource: "PricingConfig",
    action: "update",
    possession: "any",
  })
  async disconnectCustomers(
    @common.Param() params: PricingConfigWhereUniqueInput,
    @common.Body() body: CustomerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      customers: {
        disconnect: body,
      },
    };
    await this.service.updatePricingConfig({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/tiers")
  @ApiNestedQuery(PricingTierFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PricingTier",
    action: "read",
    possession: "any",
  })
  async findTiers(
    @common.Req() request: Request,
    @common.Param() params: PricingConfigWhereUniqueInput
  ): Promise<PricingTier[]> {
    const query = plainToClass(PricingTierFindManyArgs, request.query);
    const results = await this.service.findTiers(params.id, {
      ...query,
      select: {
        createdAt: true,
        flatPrice: true,
        id: true,
        maxMiles: true,
        minMiles: true,

        pricingConfig: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/tiers")
  @nestAccessControl.UseRoles({
    resource: "PricingConfig",
    action: "update",
    possession: "any",
  })
  async connectTiers(
    @common.Param() params: PricingConfigWhereUniqueInput,
    @common.Body() body: PricingTierWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tiers: {
        connect: body,
      },
    };
    await this.service.updatePricingConfig({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/tiers")
  @nestAccessControl.UseRoles({
    resource: "PricingConfig",
    action: "update",
    possession: "any",
  })
  async updateTiers(
    @common.Param() params: PricingConfigWhereUniqueInput,
    @common.Body() body: PricingTierWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tiers: {
        set: body,
      },
    };
    await this.service.updatePricingConfig({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/tiers")
  @nestAccessControl.UseRoles({
    resource: "PricingConfig",
    action: "update",
    possession: "any",
  })
  async disconnectTiers(
    @common.Param() params: PricingConfigWhereUniqueInput,
    @common.Body() body: PricingTierWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tiers: {
        disconnect: body,
      },
    };
    await this.service.updatePricingConfig({
      where: params,
      data,
      select: { id: true },
    });
  }
}
