/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { SupportRequestNote } from "./SupportRequestNote";
import { SupportRequestNoteCountArgs } from "./SupportRequestNoteCountArgs";
import { SupportRequestNoteFindManyArgs } from "./SupportRequestNoteFindManyArgs";
import { SupportRequestNoteFindUniqueArgs } from "./SupportRequestNoteFindUniqueArgs";
import { CreateSupportRequestNoteArgs } from "./CreateSupportRequestNoteArgs";
import { UpdateSupportRequestNoteArgs } from "./UpdateSupportRequestNoteArgs";
import { DeleteSupportRequestNoteArgs } from "./DeleteSupportRequestNoteArgs";
import { User } from "../../user/base/User";
import { SupportRequest } from "../../supportRequest/base/SupportRequest";
import { SupportRequestNoteService } from "../supportRequestNote.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => SupportRequestNote)
export class SupportRequestNoteResolverBase {
  constructor(
    protected readonly service: SupportRequestNoteService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "SupportRequestNote",
    action: "read",
    possession: "any",
  })
  async _supportRequestNotesMeta(
    @graphql.Args() args: SupportRequestNoteCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [SupportRequestNote])
  @nestAccessControl.UseRoles({
    resource: "SupportRequestNote",
    action: "read",
    possession: "any",
  })
  async supportRequestNotes(
    @graphql.Args() args: SupportRequestNoteFindManyArgs
  ): Promise<SupportRequestNote[]> {
    return this.service.supportRequestNotes(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => SupportRequestNote, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "SupportRequestNote",
    action: "read",
    possession: "own",
  })
  async supportRequestNote(
    @graphql.Args() args: SupportRequestNoteFindUniqueArgs
  ): Promise<SupportRequestNote | null> {
    const result = await this.service.supportRequestNote(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => SupportRequestNote)
  @nestAccessControl.UseRoles({
    resource: "SupportRequestNote",
    action: "create",
    possession: "any",
  })
  async createSupportRequestNote(
    @graphql.Args() args: CreateSupportRequestNoteArgs
  ): Promise<SupportRequestNote> {
    return await this.service.createSupportRequestNote({
      ...args,
      data: {
        ...args.data,

        authorUser: args.data.authorUser
          ? {
              connect: args.data.authorUser,
            }
          : undefined,

        supportRequest: {
          connect: args.data.supportRequest,
        },
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => SupportRequestNote)
  @nestAccessControl.UseRoles({
    resource: "SupportRequestNote",
    action: "update",
    possession: "any",
  })
  async updateSupportRequestNote(
    @graphql.Args() args: UpdateSupportRequestNoteArgs
  ): Promise<SupportRequestNote | null> {
    try {
      return await this.service.updateSupportRequestNote({
        ...args,
        data: {
          ...args.data,

          authorUser: args.data.authorUser
            ? {
                connect: args.data.authorUser,
              }
            : undefined,

          supportRequest: {
            connect: args.data.supportRequest,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => SupportRequestNote)
  @nestAccessControl.UseRoles({
    resource: "SupportRequestNote",
    action: "delete",
    possession: "any",
  })
  async deleteSupportRequestNote(
    @graphql.Args() args: DeleteSupportRequestNoteArgs
  ): Promise<SupportRequestNote | null> {
    try {
      return await this.service.deleteSupportRequestNote(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "authorUser",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getAuthorUser(
    @graphql.Parent() parent: SupportRequestNote
  ): Promise<User | null> {
    const result = await this.service.getAuthorUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => SupportRequest, {
    nullable: true,
    name: "supportRequest",
  })
  @nestAccessControl.UseRoles({
    resource: "SupportRequest",
    action: "read",
    possession: "any",
  })
  async getSupportRequest(
    @graphql.Parent() parent: SupportRequestNote
  ): Promise<SupportRequest | null> {
    const result = await this.service.getSupportRequest(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
