/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DeliveryRatingService } from "../deliveryRating.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeliveryRatingCreateInput } from "./DeliveryRatingCreateInput";
import { DeliveryRating } from "./DeliveryRating";
import { DeliveryRatingFindManyArgs } from "./DeliveryRatingFindManyArgs";
import { DeliveryRatingWhereUniqueInput } from "./DeliveryRatingWhereUniqueInput";
import { DeliveryRatingUpdateInput } from "./DeliveryRatingUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DeliveryRatingControllerBase {
  constructor(
    protected readonly service: DeliveryRatingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DeliveryRating })
  @nestAccessControl.UseRoles({
    resource: "DeliveryRating",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDeliveryRating(
    @common.Body() data: DeliveryRatingCreateInput
  ): Promise<DeliveryRating> {
    return await this.service.createDeliveryRating({
      data: {
        ...data,

        customer: data.customer
          ? {
              connect: data.customer,
            }
          : undefined,

        delivery: {
          connect: data.delivery,
        },

        driver: data.driver
          ? {
              connect: data.driver,
            }
          : undefined,
      },
      select: {
        comment: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        delivery: {
          select: {
            id: true,
          },
        },

        driver: {
          select: {
            id: true,
          },
        },

        id: true,
        stars: true,
        target: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DeliveryRating] })
  @ApiNestedQuery(DeliveryRatingFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DeliveryRating",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deliveryRatings(
    @common.Req() request: Request
  ): Promise<DeliveryRating[]> {
    const args = plainToClass(DeliveryRatingFindManyArgs, request.query);
    return this.service.deliveryRatings({
      ...args,
      select: {
        comment: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        delivery: {
          select: {
            id: true,
          },
        },

        driver: {
          select: {
            id: true,
          },
        },

        id: true,
        stars: true,
        target: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DeliveryRating })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DeliveryRating",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deliveryRating(
    @common.Param() params: DeliveryRatingWhereUniqueInput
  ): Promise<DeliveryRating | null> {
    const result = await this.service.deliveryRating({
      where: params,
      select: {
        comment: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        delivery: {
          select: {
            id: true,
          },
        },

        driver: {
          select: {
            id: true,
          },
        },

        id: true,
        stars: true,
        target: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DeliveryRating })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DeliveryRating",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDeliveryRating(
    @common.Param() params: DeliveryRatingWhereUniqueInput,
    @common.Body() data: DeliveryRatingUpdateInput
  ): Promise<DeliveryRating | null> {
    try {
      return await this.service.updateDeliveryRating({
        where: params,
        data: {
          ...data,

          customer: data.customer
            ? {
                connect: data.customer,
              }
            : undefined,

          delivery: {
            connect: data.delivery,
          },

          driver: data.driver
            ? {
                connect: data.driver,
              }
            : undefined,
        },
        select: {
          comment: true,
          createdAt: true,

          customer: {
            select: {
              id: true,
            },
          },

          delivery: {
            select: {
              id: true,
            },
          },

          driver: {
            select: {
              id: true,
            },
          },

          id: true,
          stars: true,
          target: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DeliveryRating })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DeliveryRating",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDeliveryRating(
    @common.Param() params: DeliveryRatingWhereUniqueInput
  ): Promise<DeliveryRating | null> {
    try {
      return await this.service.deleteDeliveryRating({
        where: params,
        select: {
          comment: true,
          createdAt: true,

          customer: {
            select: {
              id: true,
            },
          },

          delivery: {
            select: {
              id: true,
            },
          },

          driver: {
            select: {
              id: true,
            },
          },

          id: true,
          stars: true,
          target: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
