/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumSupportRequestActorRole } from "./EnumSupportRequestActorRole";
import { IsEnum, IsOptional, ValidateNested } from "class-validator";
import { EnumSupportRequestActorType } from "./EnumSupportRequestActorType";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { Type } from "class-transformer";
import { EnumSupportRequestCategory } from "./EnumSupportRequestCategory";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { DeliveryRequestWhereUniqueInput } from "../../deliveryRequest/base/DeliveryRequestWhereUniqueInput";
import { StringFilter } from "../../util/StringFilter";
import { SupportRequestNoteListRelationFilter } from "../../supportRequestNote/base/SupportRequestNoteListRelationFilter";
import { EnumSupportRequestPriority } from "./EnumSupportRequestPriority";
import { EnumSupportRequestStatus } from "./EnumSupportRequestStatus";
import { StringNullableFilter } from "../../util/StringNullableFilter";

@InputType()
class SupportRequestWhereInput {
  @ApiProperty({
    required: false,
    enum: EnumSupportRequestActorRole,
  })
  @IsEnum(EnumSupportRequestActorRole)
  @IsOptional()
  @Field(() => EnumSupportRequestActorRole, {
    nullable: true,
  })
  actorRole?: "DRIVER" | "DEALER" | "PRIVATE_CUSTOMER" | "ADMIN" | "OPS";

  @ApiProperty({
    required: false,
    enum: EnumSupportRequestActorType,
  })
  @IsEnum(EnumSupportRequestActorType)
  @IsOptional()
  @Field(() => EnumSupportRequestActorType, {
    nullable: true,
  })
  actorType?: "USER" | "SYSTEM";

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  assignedTo?: UserWhereUniqueInput;

  @ApiProperty({
    required: false,
    enum: EnumSupportRequestCategory,
  })
  @IsEnum(EnumSupportRequestCategory)
  @IsOptional()
  @Field(() => EnumSupportRequestCategory, {
    nullable: true,
  })
  category?:
    | "GENERAL"
    | "DELIVERY_ISSUE"
    | "SCHEDULE_CHANGE"
    | "CANCELLATION_REQUEST"
    | "PAYMENT_ISSUE"
    | "DRIVER_ISSUE"
    | "ACCOUNT_ISSUE"
    | "DISPUTE_HELP"
    | "OTHER";

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  closedAt?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: DateTimeFilter,
  })
  @Type(() => DateTimeFilter)
  @IsOptional()
  @Field(() => DateTimeFilter, {
    nullable: true,
  })
  createdAt?: DateTimeFilter;

  @ApiProperty({
    required: false,
    type: () => DeliveryRequestWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DeliveryRequestWhereUniqueInput)
  @IsOptional()
  @Field(() => DeliveryRequestWhereUniqueInput, {
    nullable: true,
  })
  delivery?: DeliveryRequestWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  message?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => SupportRequestNoteListRelationFilter,
  })
  @ValidateNested()
  @Type(() => SupportRequestNoteListRelationFilter)
  @IsOptional()
  @Field(() => SupportRequestNoteListRelationFilter, {
    nullable: true,
  })
  notes?: SupportRequestNoteListRelationFilter;

  @ApiProperty({
    required: false,
    enum: EnumSupportRequestPriority,
  })
  @IsEnum(EnumSupportRequestPriority)
  @IsOptional()
  @Field(() => EnumSupportRequestPriority, {
    nullable: true,
  })
  priority?: "LOW" | "NORMAL" | "HIGH" | "URGENT";

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  resolvedAt?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumSupportRequestStatus,
  })
  @IsEnum(EnumSupportRequestStatus)
  @IsOptional()
  @Field(() => EnumSupportRequestStatus, {
    nullable: true,
  })
  status?: "OPEN" | "IN_PROGRESS" | "RESOLVED" | "CLOSED";

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  subject?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: DateTimeFilter,
  })
  @Type(() => DateTimeFilter)
  @IsOptional()
  @Field(() => DateTimeFilter, {
    nullable: true,
  })
  updatedAt?: DateTimeFilter;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput;
}

export { SupportRequestWhereInput as SupportRequestWhereInput };
