/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumSupportRequestActorRole } from "./EnumSupportRequestActorRole";
import {
  IsEnum,
  IsOptional,
  ValidateNested,
  IsDate,
  IsString,
  MaxLength,
} from "class-validator";
import { EnumSupportRequestActorType } from "./EnumSupportRequestActorType";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { Type } from "class-transformer";
import { EnumSupportRequestCategory } from "./EnumSupportRequestCategory";
import { DeliveryRequestWhereUniqueInput } from "../../deliveryRequest/base/DeliveryRequestWhereUniqueInput";
import { SupportRequestNoteUpdateManyWithoutSupportRequestsInput } from "./SupportRequestNoteUpdateManyWithoutSupportRequestsInput";
import { EnumSupportRequestPriority } from "./EnumSupportRequestPriority";
import { EnumSupportRequestStatus } from "./EnumSupportRequestStatus";

@InputType()
class SupportRequestUpdateInput {
  @ApiProperty({
    required: false,
    enum: EnumSupportRequestActorRole,
  })
  @IsEnum(EnumSupportRequestActorRole)
  @IsOptional()
  @Field(() => EnumSupportRequestActorRole, {
    nullable: true,
  })
  actorRole?: "DRIVER" | "DEALER" | "PRIVATE_CUSTOMER" | "ADMIN" | "OPS";

  @ApiProperty({
    required: false,
    enum: EnumSupportRequestActorType,
  })
  @IsEnum(EnumSupportRequestActorType)
  @IsOptional()
  @Field(() => EnumSupportRequestActorType, {
    nullable: true,
  })
  actorType?: "USER" | "SYSTEM";

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  assignedTo?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    enum: EnumSupportRequestCategory,
  })
  @IsEnum(EnumSupportRequestCategory)
  @IsOptional()
  @Field(() => EnumSupportRequestCategory, {
    nullable: true,
  })
  category?:
    | "GENERAL"
    | "DELIVERY_ISSUE"
    | "SCHEDULE_CHANGE"
    | "CANCELLATION_REQUEST"
    | "PAYMENT_ISSUE"
    | "DRIVER_ISSUE"
    | "ACCOUNT_ISSUE"
    | "DISPUTE_HELP"
    | "OTHER";

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  closedAt?: Date | null;

  @ApiProperty({
    required: false,
    type: () => DeliveryRequestWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DeliveryRequestWhereUniqueInput)
  @IsOptional()
  @Field(() => DeliveryRequestWhereUniqueInput, {
    nullable: true,
  })
  delivery?: DeliveryRequestWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  message?: string;

  @ApiProperty({
    required: false,
    type: () => SupportRequestNoteUpdateManyWithoutSupportRequestsInput,
  })
  @ValidateNested()
  @Type(() => SupportRequestNoteUpdateManyWithoutSupportRequestsInput)
  @IsOptional()
  @Field(() => SupportRequestNoteUpdateManyWithoutSupportRequestsInput, {
    nullable: true,
  })
  notes?: SupportRequestNoteUpdateManyWithoutSupportRequestsInput;

  @ApiProperty({
    required: false,
    enum: EnumSupportRequestPriority,
  })
  @IsEnum(EnumSupportRequestPriority)
  @IsOptional()
  @Field(() => EnumSupportRequestPriority, {
    nullable: true,
  })
  priority?: "LOW" | "NORMAL" | "HIGH" | "URGENT";

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  resolvedAt?: Date | null;

  @ApiProperty({
    required: false,
    enum: EnumSupportRequestStatus,
  })
  @IsEnum(EnumSupportRequestStatus)
  @IsOptional()
  @Field(() => EnumSupportRequestStatus, {
    nullable: true,
  })
  status?: "OPEN" | "IN_PROGRESS" | "RESOLVED" | "CLOSED";

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  subject?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { SupportRequestUpdateInput as SupportRequestUpdateInput };
