/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TermsIndexRouteImport } from './routes/terms/index'
import { Route as QuoteDetailsIndexRouteImport } from './routes/quote-details/index'
import { Route as QuoteConfirmationIndexRouteImport } from './routes/quote-confirmation/index'
import { Route as PrivacyIndexRouteImport } from './routes/privacy/index'
import { Route as MapTestIndexRouteImport } from './routes/map-test/index'
import { Route as LandingIndexRouteImport } from './routes/landing/index'
import { Route as DriverWalletIndexRouteImport } from './routes/driver-wallet/index'
import { Route as DriverSigninIndexRouteImport } from './routes/driver-signin/index'
import { Route as DriverRepositioningIndexRouteImport } from './routes/driver-repositioning/index'
import { Route as DriverPreferencesIndexRouteImport } from './routes/driver-preferences/index'
import { Route as DriverPickupChecklistIndexRouteImport } from './routes/driver-pickup-checklist/index'
import { Route as DriverOnboardingIndexRouteImport } from './routes/driver-onboarding/index'
import { Route as DriverMenuIndexRouteImport } from './routes/driver-menu/index'
import { Route as DriverJobDetailsIndexRouteImport } from './routes/driver-job-details/index'
import { Route as DriverIssueReportIndexRouteImport } from './routes/driver-issue-report/index'
import { Route as DriverInboxIndexRouteImport } from './routes/driver-inbox/index'
import { Route as DriverDropoffChecklistIndexRouteImport } from './routes/driver-dropoff-checklist/index'
import { Route as DriverDashboardIndexRouteImport } from './routes/driver-dashboard/index'
import { Route as DriverActiveIndexRouteImport } from './routes/driver-active/index'
import { Route as DealerOnboardingIndexRouteImport } from './routes/dealer-onboarding/index'
import { Route as DealerDeliveryDetailsIndexRouteImport } from './routes/dealer-delivery-details/index'
import { Route as DealerDashboardIndexRouteImport } from './routes/dealer-dashboard/index'
import { Route as DealerCreateDeliveryIndexRouteImport } from './routes/dealer-create-delivery/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin-users/index'
import { Route as AdminUserDetailIndexRouteImport } from './routes/admin-user-detail/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin-settings/index'
import { Route as AdminSchedulingPolicyIndexRouteImport } from './routes/admin-scheduling-policy/index'
import { Route as AdminReportsIndexRouteImport } from './routes/admin-reports/index'
import { Route as AdminReportPaymentsIndexRouteImport } from './routes/admin-report-payments/index'
import { Route as AdminReportOpsSummaryIndexRouteImport } from './routes/admin-report-ops-summary/index'
import { Route as AdminReportDisputesIndexRouteImport } from './routes/admin-report-disputes/index'
import { Route as AdminReportDeliveriesIndexRouteImport } from './routes/admin-report-deliveries/index'
import { Route as AdminReportComplianceIndexRouteImport } from './routes/admin-report-compliance/index'
import { Route as AdminPricingIndexRouteImport } from './routes/admin-pricing/index'
import { Route as AdminPricingRuleIndexRouteImport } from './routes/admin-pricing-rule/index'
import { Route as AdminPaymentsIndexRouteImport } from './routes/admin-payments/index'
import { Route as AdminNotificationPolicyIndexRouteImport } from './routes/admin-notification-policy/index'
import { Route as AdminInsuranceReportingIndexRouteImport } from './routes/admin-insurance-reporting/index'
import { Route as AdminDisputesIndexRouteImport } from './routes/admin-disputes/index'
import { Route as AdminDisputeDetailsIndexRouteImport } from './routes/admin-dispute-details/index'
import { Route as AdminDeliveryDetailIndexRouteImport } from './routes/admin-delivery-detail/index'
import { Route as AdminDeliveriesIndexRouteImport } from './routes/admin-deliveries/index'
import { Route as AdminDealerDetailIndexRouteImport } from './routes/admin-dealer-detail/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin-dashboard/index'
import { Route as AdminConfigIndexRouteImport } from './routes/admin-config/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthDealerSignupRouteImport } from './routes/auth/dealer-signup'
import { Route as AuthDealerSigninRouteImport } from './routes/auth/dealer-signin'
import { Route as AuthAdminSigninRouteImport } from './routes/auth/admin-signin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsIndexRoute = TermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteDetailsIndexRoute = QuoteDetailsIndexRouteImport.update({
  id: '/quote-details/',
  path: '/quote-details/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteConfirmationIndexRoute = QuoteConfirmationIndexRouteImport.update({
  id: '/quote-confirmation/',
  path: '/quote-confirmation/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyIndexRoute = PrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapTestIndexRoute = MapTestIndexRouteImport.update({
  id: '/map-test/',
  path: '/map-test/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/landing/',
  path: '/landing/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverWalletIndexRoute = DriverWalletIndexRouteImport.update({
  id: '/driver-wallet/',
  path: '/driver-wallet/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverSigninIndexRoute = DriverSigninIndexRouteImport.update({
  id: '/driver-signin/',
  path: '/driver-signin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRepositioningIndexRoute =
  DriverRepositioningIndexRouteImport.update({
    id: '/driver-repositioning/',
    path: '/driver-repositioning/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DriverPreferencesIndexRoute = DriverPreferencesIndexRouteImport.update({
  id: '/driver-preferences/',
  path: '/driver-preferences/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverPickupChecklistIndexRoute =
  DriverPickupChecklistIndexRouteImport.update({
    id: '/driver-pickup-checklist/',
    path: '/driver-pickup-checklist/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DriverOnboardingIndexRoute = DriverOnboardingIndexRouteImport.update({
  id: '/driver-onboarding/',
  path: '/driver-onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverMenuIndexRoute = DriverMenuIndexRouteImport.update({
  id: '/driver-menu/',
  path: '/driver-menu/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverJobDetailsIndexRoute = DriverJobDetailsIndexRouteImport.update({
  id: '/driver-job-details/',
  path: '/driver-job-details/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverIssueReportIndexRoute = DriverIssueReportIndexRouteImport.update({
  id: '/driver-issue-report/',
  path: '/driver-issue-report/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverInboxIndexRoute = DriverInboxIndexRouteImport.update({
  id: '/driver-inbox/',
  path: '/driver-inbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverDropoffChecklistIndexRoute =
  DriverDropoffChecklistIndexRouteImport.update({
    id: '/driver-dropoff-checklist/',
    path: '/driver-dropoff-checklist/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DriverDashboardIndexRoute = DriverDashboardIndexRouteImport.update({
  id: '/driver-dashboard/',
  path: '/driver-dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverActiveIndexRoute = DriverActiveIndexRouteImport.update({
  id: '/driver-active/',
  path: '/driver-active/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealerOnboardingIndexRoute = DealerOnboardingIndexRouteImport.update({
  id: '/dealer-onboarding/',
  path: '/dealer-onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealerDeliveryDetailsIndexRoute =
  DealerDeliveryDetailsIndexRouteImport.update({
    id: '/dealer-delivery-details/',
    path: '/dealer-delivery-details/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DealerDashboardIndexRoute = DealerDashboardIndexRouteImport.update({
  id: '/dealer-dashboard/',
  path: '/dealer-dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealerCreateDeliveryIndexRoute =
  DealerCreateDeliveryIndexRouteImport.update({
    id: '/dealer-create-delivery/',
    path: '/dealer-create-delivery/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin-users/',
  path: '/admin-users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUserDetailIndexRoute = AdminUserDetailIndexRouteImport.update({
  id: '/admin-user-detail/',
  path: '/admin-user-detail/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/admin-settings/',
  path: '/admin-settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSchedulingPolicyIndexRoute =
  AdminSchedulingPolicyIndexRouteImport.update({
    id: '/admin-scheduling-policy/',
    path: '/admin-scheduling-policy/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminReportsIndexRoute = AdminReportsIndexRouteImport.update({
  id: '/admin-reports/',
  path: '/admin-reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportPaymentsIndexRoute =
  AdminReportPaymentsIndexRouteImport.update({
    id: '/admin-report-payments/',
    path: '/admin-report-payments/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminReportOpsSummaryIndexRoute =
  AdminReportOpsSummaryIndexRouteImport.update({
    id: '/admin-report-ops-summary/',
    path: '/admin-report-ops-summary/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminReportDisputesIndexRoute =
  AdminReportDisputesIndexRouteImport.update({
    id: '/admin-report-disputes/',
    path: '/admin-report-disputes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminReportDeliveriesIndexRoute =
  AdminReportDeliveriesIndexRouteImport.update({
    id: '/admin-report-deliveries/',
    path: '/admin-report-deliveries/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminReportComplianceIndexRoute =
  AdminReportComplianceIndexRouteImport.update({
    id: '/admin-report-compliance/',
    path: '/admin-report-compliance/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminPricingIndexRoute = AdminPricingIndexRouteImport.update({
  id: '/admin-pricing/',
  path: '/admin-pricing/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPricingRuleIndexRoute = AdminPricingRuleIndexRouteImport.update({
  id: '/admin-pricing-rule/',
  path: '/admin-pricing-rule/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsIndexRoute = AdminPaymentsIndexRouteImport.update({
  id: '/admin-payments/',
  path: '/admin-payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationPolicyIndexRoute =
  AdminNotificationPolicyIndexRouteImport.update({
    id: '/admin-notification-policy/',
    path: '/admin-notification-policy/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminInsuranceReportingIndexRoute =
  AdminInsuranceReportingIndexRouteImport.update({
    id: '/admin-insurance-reporting/',
    path: '/admin-insurance-reporting/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDisputesIndexRoute = AdminDisputesIndexRouteImport.update({
  id: '/admin-disputes/',
  path: '/admin-disputes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDisputeDetailsIndexRoute =
  AdminDisputeDetailsIndexRouteImport.update({
    id: '/admin-dispute-details/',
    path: '/admin-dispute-details/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDeliveryDetailIndexRoute =
  AdminDeliveryDetailIndexRouteImport.update({
    id: '/admin-delivery-detail/',
    path: '/admin-delivery-detail/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDeliveriesIndexRoute = AdminDeliveriesIndexRouteImport.update({
  id: '/admin-deliveries/',
  path: '/admin-deliveries/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDealerDetailIndexRoute = AdminDealerDetailIndexRouteImport.update({
  id: '/admin-dealer-detail/',
  path: '/admin-dealer-detail/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/admin-dashboard/',
  path: '/admin-dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfigIndexRoute = AdminConfigIndexRouteImport.update({
  id: '/admin-config/',
  path: '/admin-config/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDealerSignupRoute = AuthDealerSignupRouteImport.update({
  id: '/auth/dealer-signup',
  path: '/auth/dealer-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDealerSigninRoute = AuthDealerSigninRouteImport.update({
  id: '/auth/dealer-signin',
  path: '/auth/dealer-signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminSigninRoute = AuthAdminSigninRouteImport.update({
  id: '/auth/admin-signin',
  path: '/auth/admin-signin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/admin-signin': typeof AuthAdminSigninRoute
  '/auth/dealer-signin': typeof AuthDealerSigninRoute
  '/auth/dealer-signup': typeof AuthDealerSignupRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/about/': typeof AboutIndexRoute
  '/admin-config/': typeof AdminConfigIndexRoute
  '/admin-dashboard/': typeof AdminDashboardIndexRoute
  '/admin-dealer-detail/': typeof AdminDealerDetailIndexRoute
  '/admin-deliveries/': typeof AdminDeliveriesIndexRoute
  '/admin-delivery-detail/': typeof AdminDeliveryDetailIndexRoute
  '/admin-dispute-details/': typeof AdminDisputeDetailsIndexRoute
  '/admin-disputes/': typeof AdminDisputesIndexRoute
  '/admin-insurance-reporting/': typeof AdminInsuranceReportingIndexRoute
  '/admin-notification-policy/': typeof AdminNotificationPolicyIndexRoute
  '/admin-payments/': typeof AdminPaymentsIndexRoute
  '/admin-pricing-rule/': typeof AdminPricingRuleIndexRoute
  '/admin-pricing/': typeof AdminPricingIndexRoute
  '/admin-report-compliance/': typeof AdminReportComplianceIndexRoute
  '/admin-report-deliveries/': typeof AdminReportDeliveriesIndexRoute
  '/admin-report-disputes/': typeof AdminReportDisputesIndexRoute
  '/admin-report-ops-summary/': typeof AdminReportOpsSummaryIndexRoute
  '/admin-report-payments/': typeof AdminReportPaymentsIndexRoute
  '/admin-reports/': typeof AdminReportsIndexRoute
  '/admin-scheduling-policy/': typeof AdminSchedulingPolicyIndexRoute
  '/admin-settings/': typeof AdminSettingsIndexRoute
  '/admin-user-detail/': typeof AdminUserDetailIndexRoute
  '/admin-users/': typeof AdminUsersIndexRoute
  '/dealer-create-delivery/': typeof DealerCreateDeliveryIndexRoute
  '/dealer-dashboard/': typeof DealerDashboardIndexRoute
  '/dealer-delivery-details/': typeof DealerDeliveryDetailsIndexRoute
  '/dealer-onboarding/': typeof DealerOnboardingIndexRoute
  '/driver-active/': typeof DriverActiveIndexRoute
  '/driver-dashboard/': typeof DriverDashboardIndexRoute
  '/driver-dropoff-checklist/': typeof DriverDropoffChecklistIndexRoute
  '/driver-inbox/': typeof DriverInboxIndexRoute
  '/driver-issue-report/': typeof DriverIssueReportIndexRoute
  '/driver-job-details/': typeof DriverJobDetailsIndexRoute
  '/driver-menu/': typeof DriverMenuIndexRoute
  '/driver-onboarding/': typeof DriverOnboardingIndexRoute
  '/driver-pickup-checklist/': typeof DriverPickupChecklistIndexRoute
  '/driver-preferences/': typeof DriverPreferencesIndexRoute
  '/driver-repositioning/': typeof DriverRepositioningIndexRoute
  '/driver-signin/': typeof DriverSigninIndexRoute
  '/driver-wallet/': typeof DriverWalletIndexRoute
  '/landing/': typeof LandingIndexRoute
  '/map-test/': typeof MapTestIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/quote-confirmation/': typeof QuoteConfirmationIndexRoute
  '/quote-details/': typeof QuoteDetailsIndexRoute
  '/terms/': typeof TermsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/admin-signin': typeof AuthAdminSigninRoute
  '/auth/dealer-signin': typeof AuthDealerSigninRoute
  '/auth/dealer-signup': typeof AuthDealerSignupRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/about': typeof AboutIndexRoute
  '/admin-config': typeof AdminConfigIndexRoute
  '/admin-dashboard': typeof AdminDashboardIndexRoute
  '/admin-dealer-detail': typeof AdminDealerDetailIndexRoute
  '/admin-deliveries': typeof AdminDeliveriesIndexRoute
  '/admin-delivery-detail': typeof AdminDeliveryDetailIndexRoute
  '/admin-dispute-details': typeof AdminDisputeDetailsIndexRoute
  '/admin-disputes': typeof AdminDisputesIndexRoute
  '/admin-insurance-reporting': typeof AdminInsuranceReportingIndexRoute
  '/admin-notification-policy': typeof AdminNotificationPolicyIndexRoute
  '/admin-payments': typeof AdminPaymentsIndexRoute
  '/admin-pricing-rule': typeof AdminPricingRuleIndexRoute
  '/admin-pricing': typeof AdminPricingIndexRoute
  '/admin-report-compliance': typeof AdminReportComplianceIndexRoute
  '/admin-report-deliveries': typeof AdminReportDeliveriesIndexRoute
  '/admin-report-disputes': typeof AdminReportDisputesIndexRoute
  '/admin-report-ops-summary': typeof AdminReportOpsSummaryIndexRoute
  '/admin-report-payments': typeof AdminReportPaymentsIndexRoute
  '/admin-reports': typeof AdminReportsIndexRoute
  '/admin-scheduling-policy': typeof AdminSchedulingPolicyIndexRoute
  '/admin-settings': typeof AdminSettingsIndexRoute
  '/admin-user-detail': typeof AdminUserDetailIndexRoute
  '/admin-users': typeof AdminUsersIndexRoute
  '/dealer-create-delivery': typeof DealerCreateDeliveryIndexRoute
  '/dealer-dashboard': typeof DealerDashboardIndexRoute
  '/dealer-delivery-details': typeof DealerDeliveryDetailsIndexRoute
  '/dealer-onboarding': typeof DealerOnboardingIndexRoute
  '/driver-active': typeof DriverActiveIndexRoute
  '/driver-dashboard': typeof DriverDashboardIndexRoute
  '/driver-dropoff-checklist': typeof DriverDropoffChecklistIndexRoute
  '/driver-inbox': typeof DriverInboxIndexRoute
  '/driver-issue-report': typeof DriverIssueReportIndexRoute
  '/driver-job-details': typeof DriverJobDetailsIndexRoute
  '/driver-menu': typeof DriverMenuIndexRoute
  '/driver-onboarding': typeof DriverOnboardingIndexRoute
  '/driver-pickup-checklist': typeof DriverPickupChecklistIndexRoute
  '/driver-preferences': typeof DriverPreferencesIndexRoute
  '/driver-repositioning': typeof DriverRepositioningIndexRoute
  '/driver-signin': typeof DriverSigninIndexRoute
  '/driver-wallet': typeof DriverWalletIndexRoute
  '/landing': typeof LandingIndexRoute
  '/map-test': typeof MapTestIndexRoute
  '/privacy': typeof PrivacyIndexRoute
  '/quote-confirmation': typeof QuoteConfirmationIndexRoute
  '/quote-details': typeof QuoteDetailsIndexRoute
  '/terms': typeof TermsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/admin-signin': typeof AuthAdminSigninRoute
  '/auth/dealer-signin': typeof AuthDealerSigninRoute
  '/auth/dealer-signup': typeof AuthDealerSignupRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/about/': typeof AboutIndexRoute
  '/admin-config/': typeof AdminConfigIndexRoute
  '/admin-dashboard/': typeof AdminDashboardIndexRoute
  '/admin-dealer-detail/': typeof AdminDealerDetailIndexRoute
  '/admin-deliveries/': typeof AdminDeliveriesIndexRoute
  '/admin-delivery-detail/': typeof AdminDeliveryDetailIndexRoute
  '/admin-dispute-details/': typeof AdminDisputeDetailsIndexRoute
  '/admin-disputes/': typeof AdminDisputesIndexRoute
  '/admin-insurance-reporting/': typeof AdminInsuranceReportingIndexRoute
  '/admin-notification-policy/': typeof AdminNotificationPolicyIndexRoute
  '/admin-payments/': typeof AdminPaymentsIndexRoute
  '/admin-pricing-rule/': typeof AdminPricingRuleIndexRoute
  '/admin-pricing/': typeof AdminPricingIndexRoute
  '/admin-report-compliance/': typeof AdminReportComplianceIndexRoute
  '/admin-report-deliveries/': typeof AdminReportDeliveriesIndexRoute
  '/admin-report-disputes/': typeof AdminReportDisputesIndexRoute
  '/admin-report-ops-summary/': typeof AdminReportOpsSummaryIndexRoute
  '/admin-report-payments/': typeof AdminReportPaymentsIndexRoute
  '/admin-reports/': typeof AdminReportsIndexRoute
  '/admin-scheduling-policy/': typeof AdminSchedulingPolicyIndexRoute
  '/admin-settings/': typeof AdminSettingsIndexRoute
  '/admin-user-detail/': typeof AdminUserDetailIndexRoute
  '/admin-users/': typeof AdminUsersIndexRoute
  '/dealer-create-delivery/': typeof DealerCreateDeliveryIndexRoute
  '/dealer-dashboard/': typeof DealerDashboardIndexRoute
  '/dealer-delivery-details/': typeof DealerDeliveryDetailsIndexRoute
  '/dealer-onboarding/': typeof DealerOnboardingIndexRoute
  '/driver-active/': typeof DriverActiveIndexRoute
  '/driver-dashboard/': typeof DriverDashboardIndexRoute
  '/driver-dropoff-checklist/': typeof DriverDropoffChecklistIndexRoute
  '/driver-inbox/': typeof DriverInboxIndexRoute
  '/driver-issue-report/': typeof DriverIssueReportIndexRoute
  '/driver-job-details/': typeof DriverJobDetailsIndexRoute
  '/driver-menu/': typeof DriverMenuIndexRoute
  '/driver-onboarding/': typeof DriverOnboardingIndexRoute
  '/driver-pickup-checklist/': typeof DriverPickupChecklistIndexRoute
  '/driver-preferences/': typeof DriverPreferencesIndexRoute
  '/driver-repositioning/': typeof DriverRepositioningIndexRoute
  '/driver-signin/': typeof DriverSigninIndexRoute
  '/driver-wallet/': typeof DriverWalletIndexRoute
  '/landing/': typeof LandingIndexRoute
  '/map-test/': typeof MapTestIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/quote-confirmation/': typeof QuoteConfirmationIndexRoute
  '/quote-details/': typeof QuoteDetailsIndexRoute
  '/terms/': typeof TermsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/admin-signin'
    | '/auth/dealer-signin'
    | '/auth/dealer-signup'
    | '/auth/reset-password'
    | '/about/'
    | '/admin-config/'
    | '/admin-dashboard/'
    | '/admin-dealer-detail/'
    | '/admin-deliveries/'
    | '/admin-delivery-detail/'
    | '/admin-dispute-details/'
    | '/admin-disputes/'
    | '/admin-insurance-reporting/'
    | '/admin-notification-policy/'
    | '/admin-payments/'
    | '/admin-pricing-rule/'
    | '/admin-pricing/'
    | '/admin-report-compliance/'
    | '/admin-report-deliveries/'
    | '/admin-report-disputes/'
    | '/admin-report-ops-summary/'
    | '/admin-report-payments/'
    | '/admin-reports/'
    | '/admin-scheduling-policy/'
    | '/admin-settings/'
    | '/admin-user-detail/'
    | '/admin-users/'
    | '/dealer-create-delivery/'
    | '/dealer-dashboard/'
    | '/dealer-delivery-details/'
    | '/dealer-onboarding/'
    | '/driver-active/'
    | '/driver-dashboard/'
    | '/driver-dropoff-checklist/'
    | '/driver-inbox/'
    | '/driver-issue-report/'
    | '/driver-job-details/'
    | '/driver-menu/'
    | '/driver-onboarding/'
    | '/driver-pickup-checklist/'
    | '/driver-preferences/'
    | '/driver-repositioning/'
    | '/driver-signin/'
    | '/driver-wallet/'
    | '/landing/'
    | '/map-test/'
    | '/privacy/'
    | '/quote-confirmation/'
    | '/quote-details/'
    | '/terms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/admin-signin'
    | '/auth/dealer-signin'
    | '/auth/dealer-signup'
    | '/auth/reset-password'
    | '/about'
    | '/admin-config'
    | '/admin-dashboard'
    | '/admin-dealer-detail'
    | '/admin-deliveries'
    | '/admin-delivery-detail'
    | '/admin-dispute-details'
    | '/admin-disputes'
    | '/admin-insurance-reporting'
    | '/admin-notification-policy'
    | '/admin-payments'
    | '/admin-pricing-rule'
    | '/admin-pricing'
    | '/admin-report-compliance'
    | '/admin-report-deliveries'
    | '/admin-report-disputes'
    | '/admin-report-ops-summary'
    | '/admin-report-payments'
    | '/admin-reports'
    | '/admin-scheduling-policy'
    | '/admin-settings'
    | '/admin-user-detail'
    | '/admin-users'
    | '/dealer-create-delivery'
    | '/dealer-dashboard'
    | '/dealer-delivery-details'
    | '/dealer-onboarding'
    | '/driver-active'
    | '/driver-dashboard'
    | '/driver-dropoff-checklist'
    | '/driver-inbox'
    | '/driver-issue-report'
    | '/driver-job-details'
    | '/driver-menu'
    | '/driver-onboarding'
    | '/driver-pickup-checklist'
    | '/driver-preferences'
    | '/driver-repositioning'
    | '/driver-signin'
    | '/driver-wallet'
    | '/landing'
    | '/map-test'
    | '/privacy'
    | '/quote-confirmation'
    | '/quote-details'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/auth/admin-signin'
    | '/auth/dealer-signin'
    | '/auth/dealer-signup'
    | '/auth/reset-password'
    | '/about/'
    | '/admin-config/'
    | '/admin-dashboard/'
    | '/admin-dealer-detail/'
    | '/admin-deliveries/'
    | '/admin-delivery-detail/'
    | '/admin-dispute-details/'
    | '/admin-disputes/'
    | '/admin-insurance-reporting/'
    | '/admin-notification-policy/'
    | '/admin-payments/'
    | '/admin-pricing-rule/'
    | '/admin-pricing/'
    | '/admin-report-compliance/'
    | '/admin-report-deliveries/'
    | '/admin-report-disputes/'
    | '/admin-report-ops-summary/'
    | '/admin-report-payments/'
    | '/admin-reports/'
    | '/admin-scheduling-policy/'
    | '/admin-settings/'
    | '/admin-user-detail/'
    | '/admin-users/'
    | '/dealer-create-delivery/'
    | '/dealer-dashboard/'
    | '/dealer-delivery-details/'
    | '/dealer-onboarding/'
    | '/driver-active/'
    | '/driver-dashboard/'
    | '/driver-dropoff-checklist/'
    | '/driver-inbox/'
    | '/driver-issue-report/'
    | '/driver-job-details/'
    | '/driver-menu/'
    | '/driver-onboarding/'
    | '/driver-pickup-checklist/'
    | '/driver-preferences/'
    | '/driver-repositioning/'
    | '/driver-signin/'
    | '/driver-wallet/'
    | '/landing/'
    | '/map-test/'
    | '/privacy/'
    | '/quote-confirmation/'
    | '/quote-details/'
    | '/terms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthAdminSigninRoute: typeof AuthAdminSigninRoute
  AuthDealerSigninRoute: typeof AuthDealerSigninRoute
  AuthDealerSignupRoute: typeof AuthDealerSignupRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AboutIndexRoute: typeof AboutIndexRoute
  AdminConfigIndexRoute: typeof AdminConfigIndexRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminDealerDetailIndexRoute: typeof AdminDealerDetailIndexRoute
  AdminDeliveriesIndexRoute: typeof AdminDeliveriesIndexRoute
  AdminDeliveryDetailIndexRoute: typeof AdminDeliveryDetailIndexRoute
  AdminDisputeDetailsIndexRoute: typeof AdminDisputeDetailsIndexRoute
  AdminDisputesIndexRoute: typeof AdminDisputesIndexRoute
  AdminInsuranceReportingIndexRoute: typeof AdminInsuranceReportingIndexRoute
  AdminNotificationPolicyIndexRoute: typeof AdminNotificationPolicyIndexRoute
  AdminPaymentsIndexRoute: typeof AdminPaymentsIndexRoute
  AdminPricingRuleIndexRoute: typeof AdminPricingRuleIndexRoute
  AdminPricingIndexRoute: typeof AdminPricingIndexRoute
  AdminReportComplianceIndexRoute: typeof AdminReportComplianceIndexRoute
  AdminReportDeliveriesIndexRoute: typeof AdminReportDeliveriesIndexRoute
  AdminReportDisputesIndexRoute: typeof AdminReportDisputesIndexRoute
  AdminReportOpsSummaryIndexRoute: typeof AdminReportOpsSummaryIndexRoute
  AdminReportPaymentsIndexRoute: typeof AdminReportPaymentsIndexRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
  AdminSchedulingPolicyIndexRoute: typeof AdminSchedulingPolicyIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminUserDetailIndexRoute: typeof AdminUserDetailIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  DealerCreateDeliveryIndexRoute: typeof DealerCreateDeliveryIndexRoute
  DealerDashboardIndexRoute: typeof DealerDashboardIndexRoute
  DealerDeliveryDetailsIndexRoute: typeof DealerDeliveryDetailsIndexRoute
  DealerOnboardingIndexRoute: typeof DealerOnboardingIndexRoute
  DriverActiveIndexRoute: typeof DriverActiveIndexRoute
  DriverDashboardIndexRoute: typeof DriverDashboardIndexRoute
  DriverDropoffChecklistIndexRoute: typeof DriverDropoffChecklistIndexRoute
  DriverInboxIndexRoute: typeof DriverInboxIndexRoute
  DriverIssueReportIndexRoute: typeof DriverIssueReportIndexRoute
  DriverJobDetailsIndexRoute: typeof DriverJobDetailsIndexRoute
  DriverMenuIndexRoute: typeof DriverMenuIndexRoute
  DriverOnboardingIndexRoute: typeof DriverOnboardingIndexRoute
  DriverPickupChecklistIndexRoute: typeof DriverPickupChecklistIndexRoute
  DriverPreferencesIndexRoute: typeof DriverPreferencesIndexRoute
  DriverRepositioningIndexRoute: typeof DriverRepositioningIndexRoute
  DriverSigninIndexRoute: typeof DriverSigninIndexRoute
  DriverWalletIndexRoute: typeof DriverWalletIndexRoute
  LandingIndexRoute: typeof LandingIndexRoute
  MapTestIndexRoute: typeof MapTestIndexRoute
  PrivacyIndexRoute: typeof PrivacyIndexRoute
  QuoteConfirmationIndexRoute: typeof QuoteConfirmationIndexRoute
  QuoteDetailsIndexRoute: typeof QuoteDetailsIndexRoute
  TermsIndexRoute: typeof TermsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms/': {
      id: '/terms/'
      path: '/terms'
      fullPath: '/terms/'
      preLoaderRoute: typeof TermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote-details/': {
      id: '/quote-details/'
      path: '/quote-details'
      fullPath: '/quote-details/'
      preLoaderRoute: typeof QuoteDetailsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote-confirmation/': {
      id: '/quote-confirmation/'
      path: '/quote-confirmation'
      fullPath: '/quote-confirmation/'
      preLoaderRoute: typeof QuoteConfirmationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy/': {
      id: '/privacy/'
      path: '/privacy'
      fullPath: '/privacy/'
      preLoaderRoute: typeof PrivacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map-test/': {
      id: '/map-test/'
      path: '/map-test'
      fullPath: '/map-test/'
      preLoaderRoute: typeof MapTestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing/': {
      id: '/landing/'
      path: '/landing'
      fullPath: '/landing/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-wallet/': {
      id: '/driver-wallet/'
      path: '/driver-wallet'
      fullPath: '/driver-wallet/'
      preLoaderRoute: typeof DriverWalletIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-signin/': {
      id: '/driver-signin/'
      path: '/driver-signin'
      fullPath: '/driver-signin/'
      preLoaderRoute: typeof DriverSigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-repositioning/': {
      id: '/driver-repositioning/'
      path: '/driver-repositioning'
      fullPath: '/driver-repositioning/'
      preLoaderRoute: typeof DriverRepositioningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-preferences/': {
      id: '/driver-preferences/'
      path: '/driver-preferences'
      fullPath: '/driver-preferences/'
      preLoaderRoute: typeof DriverPreferencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-pickup-checklist/': {
      id: '/driver-pickup-checklist/'
      path: '/driver-pickup-checklist'
      fullPath: '/driver-pickup-checklist/'
      preLoaderRoute: typeof DriverPickupChecklistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-onboarding/': {
      id: '/driver-onboarding/'
      path: '/driver-onboarding'
      fullPath: '/driver-onboarding/'
      preLoaderRoute: typeof DriverOnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-menu/': {
      id: '/driver-menu/'
      path: '/driver-menu'
      fullPath: '/driver-menu/'
      preLoaderRoute: typeof DriverMenuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-job-details/': {
      id: '/driver-job-details/'
      path: '/driver-job-details'
      fullPath: '/driver-job-details/'
      preLoaderRoute: typeof DriverJobDetailsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-issue-report/': {
      id: '/driver-issue-report/'
      path: '/driver-issue-report'
      fullPath: '/driver-issue-report/'
      preLoaderRoute: typeof DriverIssueReportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-inbox/': {
      id: '/driver-inbox/'
      path: '/driver-inbox'
      fullPath: '/driver-inbox/'
      preLoaderRoute: typeof DriverInboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-dropoff-checklist/': {
      id: '/driver-dropoff-checklist/'
      path: '/driver-dropoff-checklist'
      fullPath: '/driver-dropoff-checklist/'
      preLoaderRoute: typeof DriverDropoffChecklistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-dashboard/': {
      id: '/driver-dashboard/'
      path: '/driver-dashboard'
      fullPath: '/driver-dashboard/'
      preLoaderRoute: typeof DriverDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-active/': {
      id: '/driver-active/'
      path: '/driver-active'
      fullPath: '/driver-active/'
      preLoaderRoute: typeof DriverActiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealer-onboarding/': {
      id: '/dealer-onboarding/'
      path: '/dealer-onboarding'
      fullPath: '/dealer-onboarding/'
      preLoaderRoute: typeof DealerOnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealer-delivery-details/': {
      id: '/dealer-delivery-details/'
      path: '/dealer-delivery-details'
      fullPath: '/dealer-delivery-details/'
      preLoaderRoute: typeof DealerDeliveryDetailsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealer-dashboard/': {
      id: '/dealer-dashboard/'
      path: '/dealer-dashboard'
      fullPath: '/dealer-dashboard/'
      preLoaderRoute: typeof DealerDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealer-create-delivery/': {
      id: '/dealer-create-delivery/'
      path: '/dealer-create-delivery'
      fullPath: '/dealer-create-delivery/'
      preLoaderRoute: typeof DealerCreateDeliveryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-users/': {
      id: '/admin-users/'
      path: '/admin-users'
      fullPath: '/admin-users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-user-detail/': {
      id: '/admin-user-detail/'
      path: '/admin-user-detail'
      fullPath: '/admin-user-detail/'
      preLoaderRoute: typeof AdminUserDetailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-settings/': {
      id: '/admin-settings/'
      path: '/admin-settings'
      fullPath: '/admin-settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-scheduling-policy/': {
      id: '/admin-scheduling-policy/'
      path: '/admin-scheduling-policy'
      fullPath: '/admin-scheduling-policy/'
      preLoaderRoute: typeof AdminSchedulingPolicyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-reports/': {
      id: '/admin-reports/'
      path: '/admin-reports'
      fullPath: '/admin-reports/'
      preLoaderRoute: typeof AdminReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-report-payments/': {
      id: '/admin-report-payments/'
      path: '/admin-report-payments'
      fullPath: '/admin-report-payments/'
      preLoaderRoute: typeof AdminReportPaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-report-ops-summary/': {
      id: '/admin-report-ops-summary/'
      path: '/admin-report-ops-summary'
      fullPath: '/admin-report-ops-summary/'
      preLoaderRoute: typeof AdminReportOpsSummaryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-report-disputes/': {
      id: '/admin-report-disputes/'
      path: '/admin-report-disputes'
      fullPath: '/admin-report-disputes/'
      preLoaderRoute: typeof AdminReportDisputesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-report-deliveries/': {
      id: '/admin-report-deliveries/'
      path: '/admin-report-deliveries'
      fullPath: '/admin-report-deliveries/'
      preLoaderRoute: typeof AdminReportDeliveriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-report-compliance/': {
      id: '/admin-report-compliance/'
      path: '/admin-report-compliance'
      fullPath: '/admin-report-compliance/'
      preLoaderRoute: typeof AdminReportComplianceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-pricing/': {
      id: '/admin-pricing/'
      path: '/admin-pricing'
      fullPath: '/admin-pricing/'
      preLoaderRoute: typeof AdminPricingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-pricing-rule/': {
      id: '/admin-pricing-rule/'
      path: '/admin-pricing-rule'
      fullPath: '/admin-pricing-rule/'
      preLoaderRoute: typeof AdminPricingRuleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-payments/': {
      id: '/admin-payments/'
      path: '/admin-payments'
      fullPath: '/admin-payments/'
      preLoaderRoute: typeof AdminPaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-notification-policy/': {
      id: '/admin-notification-policy/'
      path: '/admin-notification-policy'
      fullPath: '/admin-notification-policy/'
      preLoaderRoute: typeof AdminNotificationPolicyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-insurance-reporting/': {
      id: '/admin-insurance-reporting/'
      path: '/admin-insurance-reporting'
      fullPath: '/admin-insurance-reporting/'
      preLoaderRoute: typeof AdminInsuranceReportingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-disputes/': {
      id: '/admin-disputes/'
      path: '/admin-disputes'
      fullPath: '/admin-disputes/'
      preLoaderRoute: typeof AdminDisputesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dispute-details/': {
      id: '/admin-dispute-details/'
      path: '/admin-dispute-details'
      fullPath: '/admin-dispute-details/'
      preLoaderRoute: typeof AdminDisputeDetailsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-delivery-detail/': {
      id: '/admin-delivery-detail/'
      path: '/admin-delivery-detail'
      fullPath: '/admin-delivery-detail/'
      preLoaderRoute: typeof AdminDeliveryDetailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-deliveries/': {
      id: '/admin-deliveries/'
      path: '/admin-deliveries'
      fullPath: '/admin-deliveries/'
      preLoaderRoute: typeof AdminDeliveriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dealer-detail/': {
      id: '/admin-dealer-detail/'
      path: '/admin-dealer-detail'
      fullPath: '/admin-dealer-detail/'
      preLoaderRoute: typeof AdminDealerDetailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard/': {
      id: '/admin-dashboard/'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-config/': {
      id: '/admin-config/'
      path: '/admin-config'
      fullPath: '/admin-config/'
      preLoaderRoute: typeof AdminConfigIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/dealer-signup': {
      id: '/auth/dealer-signup'
      path: '/auth/dealer-signup'
      fullPath: '/auth/dealer-signup'
      preLoaderRoute: typeof AuthDealerSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/dealer-signin': {
      id: '/auth/dealer-signin'
      path: '/auth/dealer-signin'
      fullPath: '/auth/dealer-signin'
      preLoaderRoute: typeof AuthDealerSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/admin-signin': {
      id: '/auth/admin-signin'
      path: '/auth/admin-signin'
      fullPath: '/auth/admin-signin'
      preLoaderRoute: typeof AuthAdminSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthAdminSigninRoute: AuthAdminSigninRoute,
  AuthDealerSigninRoute: AuthDealerSigninRoute,
  AuthDealerSignupRoute: AuthDealerSignupRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AboutIndexRoute: AboutIndexRoute,
  AdminConfigIndexRoute: AdminConfigIndexRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminDealerDetailIndexRoute: AdminDealerDetailIndexRoute,
  AdminDeliveriesIndexRoute: AdminDeliveriesIndexRoute,
  AdminDeliveryDetailIndexRoute: AdminDeliveryDetailIndexRoute,
  AdminDisputeDetailsIndexRoute: AdminDisputeDetailsIndexRoute,
  AdminDisputesIndexRoute: AdminDisputesIndexRoute,
  AdminInsuranceReportingIndexRoute: AdminInsuranceReportingIndexRoute,
  AdminNotificationPolicyIndexRoute: AdminNotificationPolicyIndexRoute,
  AdminPaymentsIndexRoute: AdminPaymentsIndexRoute,
  AdminPricingRuleIndexRoute: AdminPricingRuleIndexRoute,
  AdminPricingIndexRoute: AdminPricingIndexRoute,
  AdminReportComplianceIndexRoute: AdminReportComplianceIndexRoute,
  AdminReportDeliveriesIndexRoute: AdminReportDeliveriesIndexRoute,
  AdminReportDisputesIndexRoute: AdminReportDisputesIndexRoute,
  AdminReportOpsSummaryIndexRoute: AdminReportOpsSummaryIndexRoute,
  AdminReportPaymentsIndexRoute: AdminReportPaymentsIndexRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
  AdminSchedulingPolicyIndexRoute: AdminSchedulingPolicyIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminUserDetailIndexRoute: AdminUserDetailIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  DealerCreateDeliveryIndexRoute: DealerCreateDeliveryIndexRoute,
  DealerDashboardIndexRoute: DealerDashboardIndexRoute,
  DealerDeliveryDetailsIndexRoute: DealerDeliveryDetailsIndexRoute,
  DealerOnboardingIndexRoute: DealerOnboardingIndexRoute,
  DriverActiveIndexRoute: DriverActiveIndexRoute,
  DriverDashboardIndexRoute: DriverDashboardIndexRoute,
  DriverDropoffChecklistIndexRoute: DriverDropoffChecklistIndexRoute,
  DriverInboxIndexRoute: DriverInboxIndexRoute,
  DriverIssueReportIndexRoute: DriverIssueReportIndexRoute,
  DriverJobDetailsIndexRoute: DriverJobDetailsIndexRoute,
  DriverMenuIndexRoute: DriverMenuIndexRoute,
  DriverOnboardingIndexRoute: DriverOnboardingIndexRoute,
  DriverPickupChecklistIndexRoute: DriverPickupChecklistIndexRoute,
  DriverPreferencesIndexRoute: DriverPreferencesIndexRoute,
  DriverRepositioningIndexRoute: DriverRepositioningIndexRoute,
  DriverSigninIndexRoute: DriverSigninIndexRoute,
  DriverWalletIndexRoute: DriverWalletIndexRoute,
  LandingIndexRoute: LandingIndexRoute,
  MapTestIndexRoute: MapTestIndexRoute,
  PrivacyIndexRoute: PrivacyIndexRoute,
  QuoteConfirmationIndexRoute: QuoteConfirmationIndexRoute,
  QuoteDetailsIndexRoute: QuoteDetailsIndexRoute,
  TermsIndexRoute: TermsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
