/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DriverAlertPreference } from "../../driverAlertPreference/base/DriverAlertPreference";
import {
  ValidateNested,
  IsOptional,
  IsDate,
  IsString,
  MaxLength,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { User } from "../../user/base/User";
import { DeliveryAssignment } from "../../deliveryAssignment/base/DeliveryAssignment";
import { AdminAuditLog } from "../../adminAuditLog/base/AdminAuditLog";
import { DriverDistrictPreference } from "../../driverDistrictPreference/base/DriverDistrictPreference";
import { DriverLocation } from "../../driverLocation/base/DriverLocation";
import { NotificationEvent } from "../../notificationEvent/base/NotificationEvent";
import { DriverPayout } from "../../driverPayout/base/DriverPayout";
import { DriverPreference } from "../../driverPreference/base/DriverPreference";
import { DeliveryRating } from "../../deliveryRating/base/DeliveryRating";
import { EnumDriverStatus } from "./EnumDriverStatus";

@ObjectType()
class Driver {
  @ApiProperty({
    required: false,
    type: () => DriverAlertPreference,
  })
  @ValidateNested()
  @Type(() => DriverAlertPreference)
  @IsOptional()
  alerts?: DriverAlertPreference | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  approvedAt!: Date | null;

  @ApiProperty({
    required: false,
    type: () => User,
  })
  @ValidateNested()
  @Type(() => User)
  @IsOptional()
  approvedBy?: User | null;

  @ApiProperty({
    required: false,
    type: () => [DeliveryAssignment],
  })
  @ValidateNested()
  @Type(() => DeliveryAssignment)
  @IsOptional()
  assignments?: Array<DeliveryAssignment>;

  @ApiProperty({
    required: false,
    type: () => [AdminAuditLog],
  })
  @ValidateNested()
  @Type(() => AdminAuditLog)
  @IsOptional()
  audits?: Array<AdminAuditLog>;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: () => [DriverDistrictPreference],
  })
  @ValidateNested()
  @Type(() => DriverDistrictPreference)
  @IsOptional()
  districts?: Array<DriverDistrictPreference>;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: () => DriverLocation,
  })
  @ValidateNested()
  @Type(() => DriverLocation)
  @IsOptional()
  location?: DriverLocation | null;

  @ApiProperty({
    required: false,
    type: () => [NotificationEvent],
  })
  @ValidateNested()
  @Type(() => NotificationEvent)
  @IsOptional()
  notifications?: Array<NotificationEvent>;

  @ApiProperty({
    required: false,
    type: () => [DriverPayout],
  })
  @ValidateNested()
  @Type(() => DriverPayout)
  @IsOptional()
  payouts?: Array<DriverPayout>;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone!: string | null;

  @ApiProperty({
    required: false,
    type: () => DriverPreference,
  })
  @ValidateNested()
  @Type(() => DriverPreference)
  @IsOptional()
  preferences?: DriverPreference | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  profilePhotoUrl!: string | null;

  @ApiProperty({
    required: false,
    type: () => [DeliveryRating],
  })
  @ValidateNested()
  @Type(() => DeliveryRating)
  @IsOptional()
  ratingsReceived?: Array<DeliveryRating>;

  @ApiProperty({
    required: true,
    enum: EnumDriverStatus,
  })
  @IsEnum(EnumDriverStatus)
  @Field(() => EnumDriverStatus, {
    nullable: true,
  })
  status?: "PENDING" | "APPROVED" | "SUSPENDED";

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: true,
    type: () => User,
  })
  @ValidateNested()
  @Type(() => User)
  user?: User;
}

export { Driver as Driver };
