/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsEnum,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { EnumDeliveryStatusHistoryActorRole } from "./EnumDeliveryStatusHistoryActorRole";
import { EnumDeliveryStatusHistoryActorType } from "./EnumDeliveryStatusHistoryActorType";
import { DeliveryRequestWhereUniqueInput } from "../../deliveryRequest/base/DeliveryRequestWhereUniqueInput";
import { EnumDeliveryStatusHistoryFromStatus } from "./EnumDeliveryStatusHistoryFromStatus";
import { EnumDeliveryStatusHistoryToStatus } from "./EnumDeliveryStatusHistoryToStatus";

@InputType()
class DeliveryStatusHistoryCreateInput {
  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  actor?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    enum: EnumDeliveryStatusHistoryActorRole,
  })
  @IsEnum(EnumDeliveryStatusHistoryActorRole)
  @IsOptional()
  @Field(() => EnumDeliveryStatusHistoryActorRole, {
    nullable: true,
  })
  actorRole?:
    | "PRIVATE_CUSTOMER"
    | "BUSINESS_CUSTOMER"
    | "DRIVER"
    | "ADMIN"
    | null;

  @ApiProperty({
    required: true,
    enum: EnumDeliveryStatusHistoryActorType,
  })
  @IsEnum(EnumDeliveryStatusHistoryActorType)
  @Field(() => EnumDeliveryStatusHistoryActorType)
  actorType!: "USER" | "SYSTEM";

  @ApiProperty({
    required: true,
    type: () => DeliveryRequestWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DeliveryRequestWhereUniqueInput)
  @Field(() => DeliveryRequestWhereUniqueInput)
  delivery!: DeliveryRequestWhereUniqueInput;

  @ApiProperty({
    required: false,
    enum: EnumDeliveryStatusHistoryFromStatus,
  })
  @IsEnum(EnumDeliveryStatusHistoryFromStatus)
  @IsOptional()
  @Field(() => EnumDeliveryStatusHistoryFromStatus, {
    nullable: true,
  })
  fromStatus?:
    | "DRAFT"
    | "QUOTED"
    | "LISTED"
    | "BOOKED"
    | "ACTIVE"
    | "COMPLETED"
    | "CANCELLED"
    | "EXPIRED"
    | "DISPUTED"
    | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  note?: string | null;

  @ApiProperty({
    required: true,
    enum: EnumDeliveryStatusHistoryToStatus,
  })
  @IsEnum(EnumDeliveryStatusHistoryToStatus)
  @Field(() => EnumDeliveryStatusHistoryToStatus)
  toStatus!:
    | "DRAFT"
    | "QUOTED"
    | "LISTED"
    | "BOOKED"
    | "ACTIVE"
    | "COMPLETED"
    | "CANCELLED"
    | "EXPIRED"
    | "DISPUTED";
}

export { DeliveryStatusHistoryCreateInput as DeliveryStatusHistoryCreateInput };
