/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DriverPreferenceService } from "../driverPreference.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DriverPreferenceCreateInput } from "./DriverPreferenceCreateInput";
import { DriverPreference } from "./DriverPreference";
import { DriverPreferenceFindManyArgs } from "./DriverPreferenceFindManyArgs";
import { DriverPreferenceWhereUniqueInput } from "./DriverPreferenceWhereUniqueInput";
import { DriverPreferenceUpdateInput } from "./DriverPreferenceUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DriverPreferenceControllerBase {
  constructor(
    protected readonly service: DriverPreferenceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DriverPreference })
  @nestAccessControl.UseRoles({
    resource: "DriverPreference",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDriverPreference(
    @common.Body() data: DriverPreferenceCreateInput
  ): Promise<DriverPreference> {
    return await this.service.createDriverPreference({
      data: {
        ...data,

        driver: {
          connect: data.driver,
        },
      },
      select: {
        city: true,
        createdAt: true,

        driver: {
          select: {
            id: true,
          },
        },

        id: true,
        radiusMiles: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DriverPreference] })
  @ApiNestedQuery(DriverPreferenceFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DriverPreference",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async driverPreferences(
    @common.Req() request: Request
  ): Promise<DriverPreference[]> {
    const args = plainToClass(DriverPreferenceFindManyArgs, request.query);
    return this.service.driverPreferences({
      ...args,
      select: {
        city: true,
        createdAt: true,

        driver: {
          select: {
            id: true,
          },
        },

        id: true,
        radiusMiles: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DriverPreference })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DriverPreference",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async driverPreference(
    @common.Param() params: DriverPreferenceWhereUniqueInput
  ): Promise<DriverPreference | null> {
    const result = await this.service.driverPreference({
      where: params,
      select: {
        city: true,
        createdAt: true,

        driver: {
          select: {
            id: true,
          },
        },

        id: true,
        radiusMiles: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DriverPreference })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DriverPreference",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDriverPreference(
    @common.Param() params: DriverPreferenceWhereUniqueInput,
    @common.Body() data: DriverPreferenceUpdateInput
  ): Promise<DriverPreference | null> {
    try {
      return await this.service.updateDriverPreference({
        where: params,
        data: {
          ...data,

          driver: {
            connect: data.driver,
          },
        },
        select: {
          city: true,
          createdAt: true,

          driver: {
            select: {
              id: true,
            },
          },

          id: true,
          radiusMiles: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DriverPreference })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DriverPreference",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDriverPreference(
    @common.Param() params: DriverPreferenceWhereUniqueInput
  ): Promise<DriverPreference | null> {
    try {
      return await this.service.deleteDriverPreference({
        where: params,
        select: {
          city: true,
          createdAt: true,

          driver: {
            select: {
              id: true,
            },
          },

          id: true,
          radiusMiles: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
